### ISSUE TITLE
Need Image Insertion in pdf`

### ISSUE THREAD

**Issue by rambabupudari** [TomRoush/PdfBox-Android#1]
Hi,

First of all very big thank to your pdfbox for android.it is very easy use jar ,who ever looking for pdf creation and merging.
From my side i have small request,can you please provide the  image insertion any where in the document.and also need to set hyperlink for images.I have checked the pdfbox java version.this features are available in java,but that is completely based on awt.please update the jar.

Is there any possible to play videos within pdf document.

Thanks in advance

**Comment by pks90** [comment]
PDJpeg cannot be resolved to a type . Even after importing all the jars.
