### ISSUE TITLE
APK size increasing drastically

### ISSUE THREAD

**Issue by rajsuvariya** [TomRoush/PdfBox-Android#103]
I am working on a Fintech app for which I needed to generate some PDFs for the user.

I used this library for that purpose, and while it is an excellent port for Apache PDFBox, the APK size of my app increased drastically by ~7MB.

On analyzing the APK, I found that a folder named "fontbox" in tom_roush had a raw size of 7.5 MB.

Is there a way to exclude particular fonts/other unnecessary files so I can reduce the size?

**Comment by shashank8293** [comment]
Yes, I had the same issue. The port is great, but APK size increases by too much.

**Comment by doomtrooper** [comment]
+1

**Comment by jverne** [comment]
FontBox is part of Apache PDFBox and, as far as I know, not optional. That is, all three PDFbox components have to be present at runtime. But this is not what is taking up that space. It is the font resources. This is probably to satisfy the PDF standard related to default fonts and international character support.

Others have taken a stab at lightening up the library: https://github.com/tripplemac/pdfbox-android-lite

It may be that these resources are not strictly necessary, depending on what you are doing. But someone who have to dig into that.

**Comment by TomRoush** [comment]
As jverne has said, fontbox is required for most of PdfBox's functionality. The reason that is is seperate is because it works as a standalone font processing library.

If for your app doesn't allow the user to input their own PDFs, you can determine which encoding fontbox will load for your PDFs. In Acrobat, Document Properties -> Fonts -> Encoding should tell you which resources will be loaded. The rest of the resources should be safe to remove.

**Comment by shashank8293** [comment]
In Acrobat, Document Properties -> Fonts -> Encoding, the type of encoding mentioned as 'Ansi'. There was no such file in Fontbox folder which I could remove. I could remove the fonts basis on the ones being used, but they do not really take up much space. I'm attaching the screenshot. Can you please help?

![c2r_downloadillustration](https://cloud.githubusercontent.com/assets/17872541/23741570/0e3eeef8-04cf-11e7-9fa2-30be7c341588.PNG)

**Comment by ameerparappurath** [comment]
@TomRoush You mentioned that we can remove the unwanted resources. But how it is possible? And when will the new 2.0 version will be coming

**Comment by norbdev** [comment]
Any update with this size issue?

**Comment by maxakash** [comment]
@ameerparappurath @norbdev The latest release of this library has these unwanted resources removed. You don't need to do anything.

**Comment by norbdev** [comment]
If I analyze the APK with the latest release (1.8.10.1 Feb 16 2019)
/assets/com: 1.7MB (fontbox 1.3MB)
/com/tom_roush: 1.5MB (fontbox: 1.1MB)

total: 3,2MB
