### ISSUE TITLE
Is there a way to use utf-16 when writing to pdf?

### ISSUE THREAD

**Issue by tomsr** [TomRoush/PdfBox-Android#104]
Hi, at the moment I use this font:
PDFont font = PDType1Font.TIMES_ROMAN.
But when writing symbols like "\u0160" or "\u012A" to PDF file (contentStream.showText("\u0160"), 
I am getting exception - "This font type only supports 8-bit code points".

Is there a way to use utf-16 encoding? Maybe another font class?

**Comment by TomRoush** [comment]
Try using a different font. LiberationSans is included with PdfBox-Android and usually has better Unicode character support. `PDFont font = PDType0Font.load(document, assetManager.open("com/tom_roush/pdfbox/resources/ttf/LiberationSans-Regular.ttf"));`

**Comment by tomsr** [comment]
Thanks, works like a charm.
