### ISSUE TITLE
PDF creation needs 30 secounds

### ISSUE THREAD

**Issue by leonschwanitz** [TomRoush/PdfBox-Android#113]
Hello,
It is normal that a PDF document with 5 sides needs 30 secounds to build?
(Yes i have used PDFBoxResourceLoader.init(MainActivity.getApp());) in my Main Activity.

**Comment by TomRoush** [comment]
It isn't unreasonable, depending on your device. The first call to PdfBox does quite a bit of initialization. Future calls shouldn't take nearly as long.
