### ISSUE TITLE
PNG with transaprency not visible in pdf visible signature

### ISSUE THREAD

**Issue by AlbertoZanatta** [TomRoush/PdfBox-Android#115]
Hi! 
First of all thanks to everyone who is working on this library -  it's a great and valuable effort - and excuse me for my bad English... I am an Italian student.
My goal is to sign a PDF with a Visible Signature and use as its appearance a Bitmap with transparency 
representing the handwritten signature itself. 
This is my code.

[code.txt](https://github.com/TomRoush/PdfBox-Android/files/1104413/code.txt)

When I compress the bitmap using a .PNG format it's not visible in the final pdf document whereas a .JPEG compress format makes it visible, but with black background as JPEG does not support transparency. PNGs without transparency do not cause the same problems.
The same happens when the stream is a FileInputStream generated from a .png file with transparency.
I do need the bitmap to show up with the right transparency properties in my pdf.
I am currently using Adobe Acrobat Reader DC to view my signed pdf documents.
Thanks for your time and patience,
Alberto

**Comment by TomRoush** [comment]
I haven't had the chance to test your code, but I hope that this is the same issue as #106. Are you using version 1.8.9.1 from jcenter? If you are, try building the latest version of the library from source. I think that that should solve your issue.

**Comment by AlbertoZanatta** [comment]
Thanks! It works brilliantly now, I had already read about #106 but I did not realize it was the same problem, my fault. 
By the way, I am rendering the pages of my pdf documents using the
