### ISSUE TITLE
createFromFile in PDImageXObject

### ISSUE THREAD

**Issue by Boubaker93** [TomRoush/PdfBox-Android#116]
Hello TomRoush,
I was working today on adding an image in an existing pdf (wich is a signature) and i found a solution (in ur sample project) by using the PDImageXObject.createFromFile wich takes as arguments a file and the document and it worked perfectly.
Then, i used the gradel to implement the library  into my project.But when i tried to use the PDImageXObject.createFromFIile function there was no sign of it.
Am i doing something wrong ?

**Comment by TomRoush** [comment]
I'm guessing that you're getting the library by using the v1.8.9.1 version that's on jcenter. `PDImageXObject.createFromFile` was added to the library after that release. You could build the library from source to get that method, but it may be easier to replicate its functionality instead. [The source is located here.](https://github.com/TomRoush/PdfBox-Android/blob/master/library/src/main/java/com/tom_roush/pdfbox/pdmodel/graphics/image/PDImageXObject.java)

**Comment by Boubaker93** [comment]
Hi TomRosh, thank you for your response. 
I did fix that problem by importing the library Model into my project and it worked nicely 👍 .
But now i found out an other problem. By using the `pdImage =PDImageXObject.createFromFile` and then i drew the image using `contents.drawImage(pdImage, 100,200);`. and The result was that the image is there but all the default texts are gone except for the fields that i defined.
**Thank you very much for helping me !**
