### ISSUE TITLE
PDFBox-Android based on PDFBox 2.0

### ISSUE THREAD

**Issue by ZphOs** [TomRoush/PdfBox-Android#117]
Hello TomRoush,
At first, thank you very much for this nice library, it is a great job.
Do you have any plans to bring your library over PDFBox 2.0 ?
Thank you,
Sebastien

**Comment by TomRoush** [comment]
Yes, I plan to update to the library to be based on the 2.0 codebase, but it will take some time to get there. Currently, the library is just about ready for a 1.8.10 release.

**Comment by frankyxcs** [comment]
Hi TomRoush,

great work yet ! Are you going to update this library to 18.10 soon ?

**Comment by TomRoush** [comment]
The code in master is fully up-to-date with 1.8.10, but there are still a few persistent bugs left that prevent it from being ready for a new release.

-----Original Message-----

**Comment by VojtechKallab** [comment]
Hi TomRoush, 
when you are planning to release new version 1.8.10 or 1.8.9.2? 
Looking forward to use it.

**Comment by TomRoush** [comment]
v1.8.10.0 has been released.

**Comment by normdoow** [comment]
@TomRoush when are you thinking that you will make the library base from PDFBox 2.0? Our main need for 2.0 is it has 256 key length encryption. Would we be able to help make this happen on your library? Thanks.

**Comment by TomRoush** [comment]
The upgrade to 2.0.0 is ongoing on the develop-2.0 branch, but I don't have an idea of how long it will take to finish everything. From a quick look through of the encryption classes, it looks like getting 256 keys to work shouldn't be too difficult, but I may be wrong and the 2.0 version of the library will be unstable for a while while the rest of the classes are getting updated.
As for helping, once the encryption classes are updated, it would be a great if you could build the develop-2.0 version of the library and test to make sure that there aren't any issues.

**Comment by TomRoush** [comment]
256 bit encryption is has been added to the develop-2.0 branch and is passing the tests

**Comment by aakashbhusal7** [comment]
set text color on pdfbox doesn't work..font size and font changes but the color remains black..any solutions @TomRoush

**Comment by TomRoush** [comment]
Closed, current version is based on PDFBox 2.0.0
