### ISSUE TITLE
How to add this project to my app?

### ISSUE THREAD

**Issue by tomluther** [TomRoush/PdfBox-Android#118]
Sorry to waste u guys time with such a simple question but I can't figure out how to add this to my project. I have added compile 'com.tom_roush:pdfbox-android:1.8.9.1' to my build.grade. When I try to use some of the methods it still doesn't reckognise them?
Maybe I have to add the libraries SpongyCastle core, prov, and pkix? How can I do this?

**Comment by jverne** [comment]
Show your build.gradle. You probably have two of them so show both.

**Comment by TomRoush** [comment]
Take a look at the sample app if you're not sure if your build.gradle is correct. Which methods in particular are you having trouble with? You shouldn't need to add the SpongyCastle libraries, Gradle will will automatically download those for you.

**Comment by tomluther** [comment]
Checked sample build gradle against mine, thanks.
