### ISSUE TITLE
Rendering a pdf file causes a crash

### ISSUE THREAD

**Issue by tomluther** [TomRoush/PdfBox-Android#119]
public class MainActivity extends AppCompatActivity {
       TextView display;
       Bitmap docDisplay;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        PDFBoxResourceLoader.init(getApplicationContext());

    }

    public void openDoc(View v) {

        try {

            PDDocument doc = PDDocument.load(getAssets().open("C3J15.pdf"));
            PDFRenderer renderer = new PDFRenderer(doc);
            docDisplay = renderer.renderImage(0, 1, Bitmap.Config.RGB_565); // This line crashes the app.
            ImageView iv = (ImageView) findViewById(R.id.imgPDF);
            iv.setImageBitmap(docDisplay);
        }
        catch(Exception e){
            e.printStackTrace();
        }

    }

}
`
![55911dfd6c7f0d4dbcf76c85cccf2dff](https://user-images.githubusercontent.com/30436326/28629420-4aeb278c-721f-11e7-8033-af8d51e78d2a.jpg)

When I call the method openDoc it crashes the app. This is all very alien to me but I think the line 
    `docDisplay = renderer.renderImage(0, 1, Bitmap.Config.RGB_565);`
is causing the crash. Cheers.

**Comment by TomRoush** [comment]
Your code looks OK. Are you using v1.8.9.1 of the library? Could you share the stacktrace of the crash or the PDF that causes it if possible?
