### ISSUE TITLE
PdfViewer porting

### ISSUE THREAD

**Issue by jyosh** [TomRoush/PdfBox-Android#12]
Any plan to port PdfViewer? I'm desperately looking for that.....

**Comment by jyosh** [comment]
Found that you have implemented PDFRenderer and PageDrawer classes and I tried following to get and display page image in an ImageView but it just displays a blank white screen

   mRenderer = new PDFRenderer(mPDDoc);
   pageBitmap = mRenderer.renderImage(pageNum);

   ImageView imageView = (ImageView)findViewById(R.id.pageImageView);
   imageView.setImageBitmap(pageBitmap);

is the image conversion implementation completed or am I missing anything?

**Comment by Birdbrain2** [comment]
Nope, that code looks right. I haven't finished the renderImage code yet.

**Comment by TomRoush** [comment]
Closed as duplicate
