### ISSUE TITLE
The load() method takes a long time to execute.

### ISSUE THREAD

**Issue by programmeraditya** [TomRoush/PdfBox-Android#120]
I tried different approaches of the load() method, but the load time was between 4 to 10 seconds. I tried loading a file with 600 pages and size of around 3 MB. I also wrote     PDFBoxResourceLoader.init(getApplicationContext()); in the Application instance class, but that doesn't seem to be helping.

**Comment by TomRoush** [comment]
load() is pretty slow in general, but it would be especially slow if you have a 600 page PDF. If you try to load it more than once in your application, is it just as slow? That would indicate that the slowness is purely from the size of the PDF and not from any initialization that PDFBox needs to do beforehand.

**Comment by programmeraditya** [comment]
It seems you are correct. I had read other issues and I assumed I was doing something wrong. The original PDFBox library loaded the same PDF within a second on Java, but I guess things are different on Android after the port. It'd be perfect if we could achieve the same load time as with the original library.
