### ISSUE TITLE
Write to location on PDF, text and image

### ISSUE THREAD

**Issue by beadk** [TomRoush/PdfBox-Android#121]
Have two questions, regrading a problem I'm having. First i would ask how to load put a image, jpg file, into the pdf, putting in a fixed placed. Secondly i would ask have to do the same with a text string. Should be note that i have worked with pdfbox 1.8.12 for java, and did get the text writing to work in the start in android studio, but now it always places my text in the button left corner.

Here is my code.
Writing text.
```           
            PDPageContentStream contentStream = new PDPageContentStream(temp, page, true, true, true);
            contentStream.beginText();
            contentStream.setFont(font, fontSize);
            contentStream.moveTextPositionByAmount(xLoc, yLoc);
            contentStream.drawString(text);
            contentStream.endText();
            contentStream.close();`
```

Placing picture.
```            
            PDPageContentStream contentStream = new PDPageContentStream(temp, page, true, true, true);
            File img = new File(vars.getRw().getPath()+"/tempSign.jpg");
            InputStream in = new FileInputStream(img);
            PDImageXObject image = JPEGFactory.createFromStream(temp, in);
            contentStream.moveTo(xLoc,yLoc);
            contentStream.drawImage(image, xLoc, yLoc);
            contentStream.close();
```

Do have these surrounded with trycatch of course, but dont know why it wont show the code probably here though.

**Comment by TomRoush** [comment]
What's the issue that you're having? The images / text don't show up on the PDF? Your code looks OK.

**Comment by beadk** [comment]
Have gotten the image to show now, turned out the scale of the image was to big, and while the text does show, it all appears in the bottom left corner of the pdf, which i dont understand why it does, as it did work for me thursday.

**Comment by beadk** [comment]
After a bit of early testing now, it does write text again where it should, but also for some reason add some at the bottom, while the text needed appears where it should.
