### ISSUE TITLE
Use api 26

### ISSUE THREAD

**Issue by juliendn** [TomRoush/PdfBox-Android#123]
Hello

I have issue using your lib into my application.
I use Android sdk 26. 

> Warning: com.tom_roush.pdfbox.rendering.PageDrawer: can't find referenced method 'boolean clipRegion(android.graphics.Region)' in library class android.graphics.Canvas

It seems that the symbol Canvas.clipRegion(Region) has been remove in this version.

see https://developer.android.com/sdk/api_diff/26/changes/android.graphics.Canvas.html for changelog

**Comment by juliendn** [comment]
Hi @TomRoush 

Ty for accepting pull request.
Do you plan to republish the merged version on maven ?

**Comment by Noble-Mushtak** [comment]
I am also a developer who uses this library, but I am still getting this error when building for API 26. I checked bintray and [the files on there seem to be a year old](https://bintray.com/birdbrain2/PdfBox-Android/PdfBox-Android#files/com/tom_roush/pdfbox-android). Will this be updated soon or should I [build the AAR from the GitHub source code](https://developer.android.com/studio/projects/android-library.html)? I have never had to deal with these issues before, so I am not sure what the best option here is. Any advice is appreciated. Thanks!

**Comment by TomRoush** [comment]
The changes haven't made it into a released version yet. It would be best if you build the AAR as I'm not sure when the next version will be released.

**Comment by roarapps** [comment]
Hello,

I noticed this was merged, is a new version coming out shortly or best to build the AAR?

**Comment by TomRoush** [comment]
v1.8.10.0 has been released and includes these changes.
