### ISSUE TITLE
How to use an existing PDF and just add to it

### ISSUE THREAD

**Issue by enkemari** [TomRoush/PdfBox-Android#124]
Hi, I'm pretty sure I'm just missing it somewhere in the example, but please explain how I can use an existing pdf in say assets, and just add text and images to it as opposed to creating a new pdf from scratch like you do with your createPdf function in the sample.

**Comment by TomRoush** [comment]
Use `PDDocument document = PDDocument.load(assetManager.open("MyDoc.pdf"));` instead of creating a new `PDDocument`. The rest of the code would be the same as in the `createPdf` sample.
