### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by frankyxcs** [TomRoush/PdfBox-Android#127]
Hi great work yet
but are you going to update this library to fix bugs  etc. or will nothing happens here anymore ?

Frank

**Comment by TomRoush** [comment]
I haven't had much to work on it lately, but yes it is still being worked on.

**Comment by frankyxcs** [comment]
Hi OK 

i have 2 proposals: 

- Fixing or finding a better font to reduce the errors with special characters. 
I have found now a free custom font and only use this now: This reduces my errors about 95 % 
PDFont pdfFont = PDType0Font.load(doc, assetManager.open("FreeSerif.ttf"));

but i have still an exception here: 
Caused by: java.lang.IllegalArgumentException: 
 
  at com.tom_roush.pdfbox.pdmodel.font.PDCIDFontType2.encode (PDCIDFontType2.java:360)
 
  at com.tom_roush.pdfbox.pdmodel.font.PDType0Font.encode (PDType0Font.java:320)
 
  at com.tom_roush.pdfbox.pdmodel.font.PDFont.encode (PDFont.java:264)
 
  at com.tom_roush.pdfbox.pdmodel.font.PDFont.getStringWidth (PDFont.java:293)

and the app crashes 



- Saving of multipages (A4) from an edittext or textview would be nice if you get this to work 

Greets Frank

**Comment by TomRoush** [comment]
1) LiberationSans is shipped with the library and should include most of the special characters you might need. This isn't clearly stated anywhere, which needs to be fixed. 

2) I have no plans to do this right now, but I might add it to the sample functions sometime in the future.
