### ISSUE TITLE
getOptionsDisplayValues

### ISSUE THREAD

**Issue by VojtechKallab** [TomRoush/PdfBox-Android#128]
public List<String> getOptionsDisplayValues()
	{
		COSBase values = getDictionary().getDictionaryObject(COSName.OPT);
		return FieldUtils.getPairableItems(values, **0**); // **1**
	}

**Comment by TomRoush** [comment]
OK, I misread the source. I believe that it was the correct the way it was originally, and the desktop version seems to agree unless I'm misreading it again. Why do you think it needs to be switched?

**Comment by VojtechKallab** [comment]
Look at method getOptions() 
When you want key, you can call this method, but when you need value, you need getOptionsDisplayValues() method. Then you need **1** instead of **0** for pairIdx. 
- class PDChoice

Now I have to do that hack:
 PDComboBox cb = (PDComboBox) pdFieldTreeNode;
((COSString)((COSArray)((COSArray)cb.getDictionary().getDictionaryObject(COSName.OPT)).get(index)).get(**1**)).getString()
 instead of
cb.getOptionsDisplayValues().get(index)

Please fix it. 

Thanks a lot.
