### ISSUE TITLE
how can fill PDF form by clicking on a filed ?

### ISSUE THREAD

**Issue by nuwanchamara** [TomRoush/PdfBox-Android#129]
I need to fill PDF form. I need to render all pages to view and user should be able to select a field and fill that filed . I am looking for  pdf viewer that can fill form? can i do that using this library?

**Comment by TomRoush** [comment]
This library is capable of rendering the pages of your PDF, giving you the locations of the fields, and filling and saving the resulting PDF. You would need create the part that would create the TextViews over the rendered image and pass the user's input into the TextViews into the corresponding PDF fields.
