### ISSUE TITLE
OutOfMemoryError when adding Images

### ISSUE THREAD

**Issue by hurzl** [TomRoush/PdfBox-Android#131]
I try to create a PDF of images, one image per page. It works well, and the files are not exceedingly large, but after 20 pages or so Ì get

```java.lang.OutOfMemoryError: Failed to allocate a 8778468 byte allocation with 6767520 free bytes and 6MB until OOM```

when I do 

```PDImageXObject pdfimage = JPEGFactory.createFromImage(pdfDoc, bitmap, 1.0f, 300);```

Is there a way to avoid this, say by saving the PDF file after every page?
```saveIncrementally``` doesn't seem to be made for this...

**Comment by hxlich** [comment]
JPEGFactory.createFromImage() is using Bitmap create api to load your image to memory, and if it is bigger than JVM heap, your app will crash with OutOfMemoryError. 
Ref: https://developer.android.com/topic/performance/graphics/load-bitmap.html
I sumbit a fix for` createFromStream()`  with this request https://github.com/TomRoush/PdfBox-Android/commit/4c19cd8899be65ea1db564682e4f64dedefd915f
You could either use `createFromStream()` or fix `createFromImage()` in your code

**Comment by hurzl** [comment]
Ok ... but I have the Bitmaps created on-the-fly. I would have to save each of them to a file, and then pass its FileInputStream to your fixed ```createFromStream()```?

**Comment by hxlich** [comment]
I tested `JPEGFactory.createFromImage()` with this snippet [https://gist.github.com/hxlich/4398bd1da5a0d98dd42f6bfee2153be8](url) , it captures screen for 1000 times and insert to pdf file. There is no memory problem in Android Studio profiler. Maybe post your crash log.

**Comment by hurzl** [comment]
I tried our snippet and get
``` 
java.lang.OutOfMemoryError: Failed to allocate a 8294412 byte allocation with 7158696 free bytes and 6MB until OOM
                                                                       at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
                                                                       at android.graphics.Bitmap.nativeCreate(Native Method)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:776)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:701)
                                                                       at android.graphics.Bitmap.createBitmap(Bitmap.java:681)
```
at ``` Bitmap snapshot = Bitmap.createBitmap(view.getDrawingCache());```

a little later (around page 105) because the screenshots are smaller than my bitmaps ...

at page 88 it starts with ```Waiting for a blocking GC Alloc```

btw why does your link link to https://github.com/TomRoush/PdfBox-Android/issues/url ?

**Comment by TomRoush** [comment]
hxlich's fix isn't yet in a released version. You'll temporarily need to build the library from source, which should take care of your memory issues.

**Comment by hurzl** [comment]
Yes I already tried the fix by just creating a PDImageXObject instead of using JPEGFactory, like the fix does.
It immediately loads the data into memory, so it has to break at sufficient number of pages

**Comment by hxlich** [comment]
hurzl, the error shows this is a general Android problem when using Bitmaps. [Handling Bitmaps](https://developer.android.com/topic/performance/graphics/index.html) may help. 

Which link are you talking about?

**Comment by hurzl** [comment]
The problem lies in the fact that the pages are not written but kept in memory. iText for example can handle as many pages as I want.
