### ISSUE TITLE
clipRegion

### ISSUE THREAD

**Issue by VojtechKallab** [TomRoush/PdfBox-Android#136]
SDK 27
Class PageDrawer, method setClip()
canvas.clipRegion(clippingPath);  clipRegion is now missing
https://developer.android.com/sdk/api_diff/26/changes/android.graphics.Canvas.html 
Please fix it.

**Comment by VojtechKallab** [comment]
Please, when you can build new version with this fix?

Thanks a lot

**Comment by TomRoush** [comment]
Fixed in release 1.8.10.0.
