### ISSUE TITLE
Image to PDF converted successfully but can't open in most of the viewers

### ISSUE THREAD

**Issue by davdavarshal** [TomRoush/PdfBox-Android#137]
I am generating pdf from many images from android app. But pdf can't be opened in PDF viewer on desktop in most of the famous viewers like Adobe, Foxit, while it opens in chrome. I am then trying to print it using Java Print API, but it gives blank pages. PDF opens in Android mobile.
Can anyone help me?

Thanks

**Comment by TomRoush** [comment]
That's strange. Can you share the PDF and/or some of the code you use to generate it?

**Comment by davdavarshal** [comment]
Here is my code snippet : 
PDDocument document = new PDDocument();
PDPage page = new PDPage();
      PDPageContentStream contentStream;
               contentStream = new PDPageContentStream(document, page);

               InputStream alpha = new FileInputStream(new File(mainpath + File.separator + allFiles[i].getName()));
               Bitmap alphaImage = BitmapFactory.decodeStream(alpha);
               PDImageXObject ximage = JPEGFactory.createFromImage(document, alphaImage);

               page.setMediaBox(new PDRectangle(ximage.getWidth(), ximage.getHeight()));
               contentStream.drawImage(ximage, 0,0);
               contentStream.fill();
               contentStream.close();
               document.addPage(page);
               document.save(output);
               document.close();

**Comment by Gvdpoel** [comment]
I'm having the same issue. I have two images in a pdf, an image from the camera which displays correctly, and a signature generated from https://github.com/gcacace/android-signaturepad

The camera image displays correctly, but the generated signature does not appear in adobe acrobat reader, but appears in chrome and preview.
[sig trst1516157847.pdf](https://github.com/TomRoush/PdfBox-Android/files/1637689/sig.trst1516157847.pdf)

**Comment by Gvdpoel** [comment]
I found a disgusting work around that makes no sense. Converting the bitmap to a string and back again fixed the issue for me.

Bitmap sig = StringToBitMap(BitMapToString(sigBitmap));

        public Bitmap StringToBitMap(String encodedString){
            try {
                byte [] encodeByte= Base64.decode(encodedString,Base64.DEFAULT);
                Bitmap bitmap=BitmapFactory.decodeByteArray(encodeByte, 0, encodeByte.length);
                return bitmap;
            } catch(Exception e) {
                e.getMessage();
                return null;
            }
        }

        public String BitMapToString(Bitmap bitmap){
            ByteArrayOutputStream baos=new  ByteArrayOutputStream();
            bitmap.compress(Bitmap.CompressFormat.PNG,100, baos);
            byte [] b=baos.toByteArray();
            String temp=Base64.encodeToString(b, Base64.DEFAULT);
            return temp;
        }

**Comment by TomRoush** [comment]
@davdavarshal I've run your code at it worked just fine.

Can either of you provide the image that seems to be causing the problem?

**Comment by THausherr** [comment]
The SMask (`Root/Pages/Kids/[0]/Resources/XObject/Im2/SMask`) image stream is empty. So something went wrong related to processing the alpha of the original image. Your `Bitmap alphaImage` is an RGBA image, and something went wrong processing the A part. This should be debugged. And yes, it would be useful to get the image.
