### ISSUE TITLE
What is min Android SDK that can be set and still be able to use this?

### ISSUE THREAD

**Issue by EvanSevy** [TomRoush/PdfBox-Android#142]
What is min Android SDK that can be set and still be able to use this?

**Comment by TomRoush** [comment]
The highest API level used in the library is 19. However, this is only one line and it is the only line in the library (I think) that uses anything above API 9.

**Comment by esutton** [comment]
@TomRoush Thank you for sharing your work!  I am going to try it out today after seeing API 19 and later is supported.

Perhaps add to readme?

> Supports Android KitKat 4.4 - 4.4.4 API level 19 and later.

I understand Apache PdfBox does not support HTML but it sounds like it may have more features than [Android PdfDocument](https://developer.android.com/reference/android/graphics/pdf/PdfDocument.html)

Finding a closed source compatible HTML to PDF library for Android is surprisingly difficult.  
iOS has decent HTML to PDF with CSS support that works well with ````<table>```` and images.
Android not-so-much. :-(

**Comment by TomRoush** [comment]
Added to the README.
