### ISSUE TITLE
How to use pdf template generate a new pdf file

### ISSUE THREAD

**Issue by fukai2952** [TomRoush/PdfBox-Android#143]
I  want to use a pdf template that contains some key such as ${XXX}  ,pass a Map that contains keys and words （eg:XXX=>Hello），then it could genertate a new pdf.  

sorry for my poor English.

**Comment by TomRoush** [comment]
The simplest way would be to make your template PDF a form and have a form field each time you have something you want to fill in. You can then flatten the form so it isn't editable anymore. If for some reason you can't do that, you would need to try to use PDFTextStripper to find your key phrases, but that would be much more difficult.

**Comment by fukai2952** [comment]
Thank you very much! I found the example and  got it.
