### ISSUE TITLE
Encoding/encryption processing

### ISSUE THREAD

**Issue by msureshmewara** [TomRoush/PdfBox-Android#147]
Dear TomRoush,

Thank you for your support.

I just want to know that this library using any Encoding/encryption processing, if yes could you please give some information about it, if possible.

Thanks in advance.

**Comment by TomRoush** [comment]
Yes, this library supports PDF encryption/decryption. What is it that you'd like to do? [Take a look here for a basic example of encryption.](https://pdfbox.apache.org/1.8/cookbook/encryption.html)
