### ISSUE TITLE
Initialization vectors should be randomly generated for proper security guarantees.

### ISSUE THREAD

**Issue by naskovai** [TomRoush/PdfBox-Android#152]
Hello,

As part of some research about the [common crypto mistakes that developers make](https://littlemaninmyhead.wordpress.com/2017/04/22/top-10-developer-crypto-mistakes/), I noticed that your application has one of them.

In [StandardSecurityHandler.prepareEncryptionDictRev6](https://github.com/TomRoush/PdfBox-Android/blob/2e1fe1ee7ab074e2cadbfc0a1f9c452e5605c73d/library/src/main/java/com/tom_roush/pdfbox/pdmodel/encryption/StandardSecurityHandler.java#L393) you're initializing Cipher instances with a static IV of 0s which is insecure. More details about this issue and how to fix it are available [here](https://doridori.github.io/Android-Security-Beware-of-the-default-IV/#sthash.SoPUiacY.dpbs).

**Comment by THausherr** [comment]
Surprisingly, this isn't a bug. See
http://intranet.pdfa.org/wp-content/uploads/2016/08/ISO_DIS_32000-2-DIS4.pdf
go to page 98 and look for "Algorithm 8" and "Algorithm 9". An IV of zero is required here. This is a draft so maybe the final specification is different, but until anybody gets to see it, that's the way it is. The (older) "supplement to the ISO 32000 specification" has the same, just search for "initialization vector of zero" there (algorithm numbers are different)
