### ISSUE TITLE
Merge PDFs produces blank pages

### ISSUE THREAD

**Issue by robbyl** [TomRoush/PdfBox-Android#155]
Merge PDFs produces blank pages for version v1.8.10.0 but the older version v1.8.9.1 works fine. Please see attached sample PDFs
[huge pdf-Page11.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957648/huge.pdf-Page11.pdf)
[huge pdf-Page12.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957649/huge.pdf-Page12.pdf)
[huge pdf-Page13.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957650/huge.pdf-Page13.pdf)
[huge pdf-Page14.pdf](https://github.com/TomRoush/PdfBox-Android/files/1957651/huge.pdf-Page14.pdf)

**Comment by TomRoush** [comment]
Possible duplicate of #130 and #133.

**Comment by markfried96** [comment]
I have the same problem.. Are there any updates since April?

**Comment by TomRoush** [comment]
The issue has been fixed in the develop-2.0 branch and the fix will be available with the 2.0 release.

**Comment by TomRoush** [comment]
Closing as 2.0.0.0 is now released
