### ISSUE TITLE
RuntimePermission for saving on Android Version 23+

### ISSUE THREAD

**Issue by philippbb** [TomRoush/PdfBox-Android#158]
On my android version (27) runtime permissions are needed to allow saving the pdf to external storage.

In the sample's mainactivity java I wanted to add those but I need to upgrade the min SDK in the gradle and manifest to use functions like ActivityCompat.requestPermissions(). 

Now I got lost a bit on how exactly to upgrade this project so I can use latest sdk in the sample?

Any advice? Thanks.

**Comment by philippbb** [comment]
Ok after updating SDK and everything in Android Studio saving with runtime permissions worked with following changes for API 24:

build.grade of sample module
- compileSdkVersion 24
- removing buildToolsVersion 
- implementation 'com.android.support:appcompat-v7:24+'

And thats all I think. ;)

**Comment by TomRoush** [comment]
Closing as this is no longer an issue with the current version
