### ISSUE TITLE
How to center align text in a textfield while using acroform

### ISSUE THREAD

**Issue by dhaneshKmPersonal** [TomRoush/PdfBox-Android#159]
Is there a way i can specify the alignment of a text in PDTextfield in a PDAcroform?
I tried using the Quad constants but, doesn't work.

`textField.q = QUADDING_CENTERED`

**Comment by TomRoush** [comment]
The function call should be `textfield.setQ(QUADDING_CENTERED)`, does that solve the problem?

**Comment by dhaneshKmPersonal** [comment]
I had to call `textField.acroForm.q = QUADDING_CENTERED` and it worked. I am using Kotlin and so used this syntax.
