### ISSUE TITLE
Not able to specify AppendMode.PREPEND to PDPageContentStream

### ISSUE THREAD

**Issue by jcinco** [TomRoush/PdfBox-Android#162]
Using the PDPageContentStream in the standard PdfBox lib allows you to specify the AppendModes: APPEND, PREPEND, and OVERWRITE. In this library, it seems that this snippet:
` if (appendContentMode.isPrepend()){
                array.add(0, contentsToAppend.getCOSObject());}
            else
            {
                array.add(contentsToAppend);
            }`
is not found in the constructor: 
`public PDPageContentStream(PDDocument document, PDPage sourcePage, AppendMode appendContentMode,
                                boolean compress, boolean resetContext) throws IOException`

**Comment by TomRoush** [comment]
The `AppendMode` enum was added in v2.0.0. This library is currently based on v1.8.10. The constructor declaration is `public PDPageContentStream(PDDocument document, PDPage sourcePage, boolean appendContent, boolean compress, boolean resetContext) throws IOException` where `appendContent` determines if the data will append or overwrite.

**Comment by TomRoush** [comment]
Closing, versions 2,0.0.0 and later have `AppendMode`
