### ISSUE TITLE
PDFieldTreeNode has been removed from latest release v1.8.10.0

### ISSUE THREAD

**Issue by aouledissa** [TomRoush/PdfBox-Android#163]
After using the library as a separate project (internally compiled) I have decided to pull it instead from your repository in order to stay up to date. The problem rises with the last version `v1.8.10.0` where i can't find the class named `PDFieldTreeNode`. Here is what i'm trying to achieve so far, so please advise how can i migrate the following snippet to use the latest release of PDF-Box Android.
`private void setValueField(PDPageContentStream contentStream, PDFieldTreeNode field, String value, int fontSize) {
        if (value != null) {
            try {

                contentStream.beginText();
                PDFont font = setFont(contentStream, fontSize);
                contentStream.setFont(font, fontSize);

                float leading = 1.5f * fontSize;

                float titleWidth = font.getStringWidth(value) / 1000f * fontSize;
                float titleHeight = font.getFontDescriptor().getFontBoundingBox().getHeight() / 1000f * fontSize * 0.865f;

                float startX = field.getWidget().getRectangle().getLowerLeftX();
                float startY = field.getWidget().getRectangle().getLowerLeftY() + (titleHeight) / 2;

                List<String> lines = new ArrayList<String>();
                int lastSpace = -1;
                while (value.length() > 0) {
                    int spaceIndex = value.indexOf(' ', lastSpace + 1);
                    if (spaceIndex < 0) {
                        if (lastSpace == -1)
                            spaceIndex = value.length() > 80 ? 80 : value.length();
                        else spaceIndex = value.length();
                    }
                    String subString = value.substring(0, spaceIndex);
                    float size = fontSize * font.getStringWidth(subString) / 1000;
                    if (size > field.getWidget().getRectangle().getWidth()) {
                        if (lastSpace < 0)
                            lastSpace = spaceIndex;
                        subString = value.substring(0, lastSpace);
                        lines.add(subString);
                        value = value.substring(lastSpace).trim();
                        lastSpace = -1;
                    } else if (spaceIndex == value.length()) {
                        lines.add(value);
                        value = "";
                    } else {
                        lastSpace = spaceIndex;
                    }
                }

                contentStream.newLineAtOffset(startX, startY);
                for (String line : lines) {
                    contentStream.showText(line);
                    contentStream.newLineAtOffset(0, -leading);
                }

                contentStream.endText();

            } catch (IOException e) {
                e.printStackTrace();
                try {
                    contentStream.endText();
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }
        }
    }`

**Comment by TomRoush** [comment]
`getWidget` and probably any other `PDFieldTreeNode` methods you may need can be found in `PDTerminalField`.
