### ISSUE TITLE
What can I do to make text stroke with current release

### ISSUE THREAD

**Issue by Devadaru** [TomRoush/PdfBox-Android#164]
Previously, I used PDPageContentStream.appendRawCommands("1 Tr\n") to make text stroke. 
But, now PDPageContentStream.appendRawCommands() deprecated. So, what can I do to make text stroke with current release.

**Comment by TomRoush** [comment]
`appendRawCommands()` won't be removed for a while as it has yet to be removed from the desktop version, so it is still safe to use. The current way to make a text stroke would be to use `PDTextState.setRenderingMode(RenderingMode.STROKE)`.
