### ISSUE TITLE
Impossible to setValue for multiple PDTextField

### ISSUE THREAD

**Issue by yuvalldb** [TomRoush/PdfBox-Android#169]
I'm using this library to edit an existing PDF form.
I got 3 different TextFields at the form and trying to edit all those 3 within the code:

```
PDDocument document = PDDocument.load(assetManager.open("TestForm.pdf"));
PDDocumentCatalog docCatalog = document.getDocumentCatalog();
PDAcroForm acroForm = docCatalog.getAcroForm();

PDTextField field = (PDTextField) acroForm.getField("Check1");
field.setValue("1111");

PDTextField field2 = (PDTextField) acroForm.getField("Check2");
field2.setValue("2222");

PDTextField field3 = (PDTextField) acroForm.getField("HelloWorld");
field3.setValue("HelloWorld");
```

For some reason only the first value will change even though all the other attributes exist at the form and I can see that this fields assigned and have values (non null).

So in the end I get a form only with "1111" TextField while the others seems to be blank
link to pdf: https://ufile.io/z8jzj

**Comment by horvathT** [comment]
Any luck finding a solution? I have the same problem except I can't edit them at all

**Comment by wildman12** [comment]
Having same issue - only first form field value is shown. Even though in page renderer annotations do have values

**Comment by TomRoush** [comment]
Closing, multiple Acroform values now show up both when the PDF is saved with filled values and if the filled form is rendered to an image
