### ISSUE TITLE
Multiple Bitmap picture generate pdf documents,and the speed is slow.

### ISSUE THREAD

**Issue by tany2018** [TomRoush/PdfBox-Android#175]
Hello!

Thank you a lot for the library.
When I am using the library you created to create a PDF with a few pictures，I find that “LosslessFactory.createFromImage(doc,pagePicture);” will takes about three seconds.Can this speed be optimized?
“JPEGFactory.createFromImage(doc, pagePicture, 1.0f);” is fast but the picture quality is bad。

**Comment by THausherr** [comment]
Use the LosslessFactory instead.

**Comment by THausherr** [comment]
If your pictures are in JPEG files, then the best way to work is to use `JPEGFactory.createFromStream()`.
