### ISSUE TITLE
Fill document not closed

### ISSUE THREAD

**Issue by SalvatoreAD** [TomRoush/PdfBox-Android#176]
Hello, by filling in the fields in my pdf template, I noticed that the created pdf document is not closed and the following error appears:

`java.io.IOException: COSStream has been closed and can not be read. Perhaps its enclosing PDDocument has been closed?`

I realized it when I tried to make a renderimage of the closed document.

Can you help me?

This is my code:

`
        PDFBoxResourceLoader.init(context);        
        PDFMergerUtility ut = new PDFMergerUtility();

            PDDocument pdfDest = new PDDocument();

            //Leggo Template
            PDDocument document = PDDocument.load(templateDefault);

            PDDocumentCatalog docCatalog = document.getDocumentCatalog();
            PDAcroForm acroForm = docCatalog.getAcroForm();

            for (Map.Entry<String, String> item : data.entrySet()) {
                String key = item.getKey();
                PDField field = acroForm.getField(key);
                if (field != null) {

                    Crashlytics.log(0, "fillPDF", "Form field with placeholder name: '" + key + "' found");
                    Log.d("fillPDF", "Form field with placeholder name: '" + key + "' found");

                    if (field instanceof PDTextField) {

                        Crashlytics.log(0, "fillPDF", "(type: " + field.getClass().getSimpleName() + ")");
                        Log.d("fillPDF", "(type: " + field.getClass().getSimpleName() + ")");

                        ((PDTextField) field).setValue(item.getValue());
                        field.setReadOnly(true);

                        Crashlytics.log(0, "fillPDF", "value is set to: '" + item.getValue() + "'");
                        Log.d("fillPDF", "value is set to: '" + item.getValue() + "'");

                    } else if (field instanceof PDPushButton) {

                        Crashlytics.log(0, "fillPDF", "(type: " + field.getClass().getSimpleName() + ")");
                        Log.d("fillPDF", "(type: " + field.getClass().getSimpleName() + ")");

                        PDPushButton pdPushButton = (PDPushButton) field;

                        List<PDAnnotationWidget> widgets = pdPushButton.getWidgets();
                        if (widgets != null && widgets.size() > 0) {
                            PDAnnotationWidget annotationWidget = widgets.get(0); // just need one widget

                            String filePath = item.getValue();
                            File imageFile = new File(pathImageFirma + filePath);

                            if (imageFile.exists()) {

                                PDImageXObject pdImageXObject = PDImageXObject.createFromFile(imageFile, document);
                                float imageScaleRatio = (float) pdImageXObject.getHeight() / (float) pdImageXObject.getWidth();

                                PDRectangle buttonPosition = getFieldArea(pdPushButton);
                                float height = buttonPosition.getHeight();
                                float width = height / imageScaleRatio;
                                float x = buttonPosition.getLowerLeftX();
                                float y = buttonPosition.getLowerLeftY();

                                PDAppearanceStream pdAppearanceStream = new PDAppearanceStream(document);
                                pdAppearanceStream.setResources(new PDResources());
                                try (PDPageContentStream pdPageContentStream = new PDPageContentStream(document, pdAppearanceStream)) {
                                    pdPageContentStream.drawImage(pdImageXObject, x, y, width, height);
                                }
                                pdAppearanceStream.setBBox(new PDRectangle(x, y, width, height));

                                PDAppearanceDictionary pdAppearanceDictionary = annotationWidget.getAppearance();
                                if (pdAppearanceDictionary == null) {
                                    pdAppearanceDictionary = new PDAppearanceDictionary();
                                    annotationWidget.setAppearance(pdAppearanceDictionary);
                                }

                                pdAppearanceDictionary.setNormalAppearance(pdAppearanceStream);
                                Crashlytics.log(0, "fillPDF", "Image '" + filePath + "' inserted");
                                Log.d("fillPDF", "Image '" + filePath + "' inserted");

                            } else {
                                Crashlytics.log(0, "fillPDF", "File " + filePath + " not found");
                                Log.d("fillPDF", "File " + filePath + " not found");
                            }
                        } else {
                            Crashlytics.log(0, "fillPDF", "Missconfiguration of placeholder: '" + key + "' - no widgets(actions) found");
                            Log.e("fillPDF", "Missconfiguration of placeholder: '" + key + "' - no widgets(actions) found");
                        }
                    } else {
                        Crashlytics.log(0, "fillPDF", "Unexpected form field type found with placeholder name: '" + key + "'");
                        Log.e("fillPDF", "Unexpected form field type found with placeholder name: '" + key + "'");
                    }
                } else {
                    Crashlytics.log(0, "fillPDF", "No field found with name:" + key);
                    Log.e("fillPDF", "No field found with name:" + key);
                }
            }

            //Chiudo document
            ut.appendDocument(pdfDest, document);
            document.close();

            long substart = System.currentTimeMillis();
            File output = new File(pathFileFirma, nomeFileFirma);
            pdfDest.save(output);
            Log.d("formData", "save took " + (System.currentTimeMillis() - substart) / 1000);
            pdfDest.close();
            templateDefault.close();

            PDFRenderer renderer = new PDFRenderer(document);
            // Render the image to an RGB Bitmap
            Bitmap pageImage = renderer.renderImage(0, 1, Bitmap.Config.RGB_565);

            // Save the render result to an image
            File renderFile = new File(pathFileFirma, nomeFileImmagineFirma);
            FileOutputStream fileOut = new FileOutputStream(renderFile);
            pageImage.compress(Bitmap.CompressFormat.JPEG, 100, fileOut);
            fileOut.close();

            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }`

**Comment by THausherr** [comment]
1) Please post the stack trace
2) Tell where the exception happens in the code above
3) Don't do a merge on unsaved files. Save them and then do the merge.
4) If the exception happens when saving, please look at the half-saved PDF file and post the last few lines of the file, starting with the line that has " obj" in it.
