### ISSUE TITLE
Arabic language is destroying xref or something..

### ISSUE THREAD

**Issue by devjta** [TomRoush/PdfBox-Android#177]
I use pdfbox, to place a Bitmap (in my case a signature) on an existing PDF.

This works fine for every country, but when setting the Emulator to AR(ar - arabic) it will work for the first time.

When I try to reopen the PDF with pdfbox, it will result in this crash:
`java.io.IOException: java.lang.NumberFormatException: For input string: "??????????"
        at com.tom_roush.pdfbox.pdfparser.COSParser.parseXrefTable(COSParser.java:1978)
        at com.tom_roush.pdfbox.pdfparser.COSParser.parseXref(COSParser.java:230)
        at com.tom_roush.pdfbox.pdfparser.PDFParser.initialParse(PDFParser.java:223)
        at com.tom_roush.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:264)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:909)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:855)
        at com.tom_roush.pdfbox.pdmodel.PDDocument.load(PDDocument.java:796)`

Also the site get-metadata.com says that the PDF has a warning with: Invalid xref table.

When I use the same app, but english language or russian, it has no problem. Also get-metadata.com doesnt show any warning..

Just try it in an emulator. For SimpleDateFormat you pass the Locale.English, because otherwise it would result in arabic numbers.. So, maybe something with just numbers? 

I can upload a working PDF and a bad PDF if you cannot reproduce it. But just change your emulator to AR, open a PDF and place a bitmap on it. Save it and try to reopen it again..

**Comment by devjta** [comment]
Just debugged a little bit and it looks like it writes arabic numbers (with arabic signs) and not latin-numbers into the XRef part..

IMHO the problem is located in class: COSWriter
`    private final NumberFormat formatXrefOffset = new DecimalFormat("0000000000");

    // the decimal format for the xref object generation number data
    private final NumberFormat formatXrefGeneration = new DecimalFormat("00000");

    private final NumberFormat formatDecimal = NumberFormat.getNumberInstance( Locale.US );`

It even says it is for generating the xref stuff.. 

Probably the error happens in the "writeXrefEntry" in the same class:
`    private void writeXrefEntry(COSWriterXRefEntry entry) throws IOException
    {
        String offset = formatXrefOffset.format(entry.getOffset());
        String generation = formatXrefGeneration.format(entry.getKey().getGeneration());`

The offset and generation can be non-latin numbers..

**Comment by devjta** [comment]
Ok, here is the fix:
`    private final NumberFormat formatXrefOffset = NumberFormat.getNumberInstance( Locale.US );

    // the decimal format for the xref object generation number data
    private final NumberFormat formatXrefGeneration = NumberFormat.getNumberInstance( Locale.US );

    private final NumberFormat formatDecimal = NumberFormat.getNumberInstance( Locale.US );`

So every numberformat would use the US signs/letters.

Then in the constructor apply the pattern:

`((DecimalFormat)formatXrefOffset).applyPattern("0000000000");
        ((DecimalFormat)formatXrefGeneration).applyPattern("00000");`

**Comment by THausherr** [comment]
There may be more to do:
https://issues.apache.org/jira/browse/PDFBOX-3481
e.g. change all occurences of String.format().

**Comment by devjta** [comment]
Well all I can say is, that after this fixes at least adding a bitmap and saving it works fine. But it would make sense, that everywhere something is formatted without adding a fixed Locale the bug could occur.
