### ISSUE TITLE
Change pdf  page orientation.

### ISSUE THREAD

**Issue by thawhtetkaung-private** [TomRoush/PdfBox-Android#180]
I found that the default size of pdf page is Letter and I found there is other size definition in library.
But I doesn't found to use them. How to apply A4 size pdf page? I want to know how to orientate the page if possible.
Update - I found the way to use A4. But doesn't know how to orientate landscape.

**Comment by TomRoush** [comment]
The code below should do what you need.
```
PDDocument doc = new PDDocument()); // Or load one
PDPage page = new PDPage(PDRectangle.A4); // Make a new A4 page
page.setRotation(90); // Rotate the page 90 degrees
doc.addPage(page); // Add the new page to the document
```

**Comment by thawhtetkaung-private** [comment]
Thanks for your answer and it solve the problem. However, when I add image to page, the image doesn't add correctly according to page rotation. I need to change image orientation.
But it is OK.
