### ISSUE TITLE
Written annotations are unrenderable for varied page dimensions

### ISSUE THREAD

**Issue by steve3d7** [TomRoush/PdfBox-Android#183]
Adding annotation to first page of document, yet if first page has different page dimensions than other pages in document, though the annotation is added to document, it cannot be read by any reader.   Seems that library is internally considering the first page to have dimensions of other pages (perhaps last page?) rather than its own defined MediaBox.  So the annotations are renderable if they fall into the mediabox of the 2nd through last pages, though they are added to the 1st page.  Is there a setting to override this behavior, or a workaround?  Can you confirm this is a bug?

**Comment by TomRoush** [comment]
I haven't been able to replicate this issue. Can you share the snippet of code that's causing the issue? In my testing, the annotations on the second page were in the same locations no matter what size the first page was and the PDF opened with no problems.
