### ISSUE TITLE
Is flattening is possible?

### ISSUE THREAD

**Issue by phanisai4u** [TomRoush/PdfBox-Android#184]
@TomRoush , Thanks for great work, is it possible flatten pdf form after filling the file with this framework. if it possible can you provide one sample it will really helpful for me.
Thanks.

**Comment by TomRoush** [comment]
In the current release version, you can use `PDField.setReadOnly(true)`, which is shown in [the sample project here](https://github.com/TomRoush/PdfBox-Android/blob/f344a164233b297c90b02ad6e67ef157df3418f3/sample/src/main/java/com/tom_roush/pdfbox/sample/MainActivity.java#L208). You would need to call that method on each field you want to flatten. After the 2.0 version is released, or if you would like to build the library from the develop-2.0 branch, you can use `PDAcroForm.flatten()` to flatten the entire AcroForm at once.

**Comment by phanisai4u** [comment]
Thanks for reply @TomRoush, when we can except the 2.o release just for my information. again thanks.

**Comment by TomRoush** [comment]
The rendering package is the only one that hasn't been updated yet. I don't have an estimate for when that will be done, but the 2.0 release will be soon after that.
