### ISSUE TITLE
resources.getImages()  is not working.

### ISSUE THREAD

**Issue by cannizarro** [TomRoush/PdfBox-Android#186]
I want to take a particular image from my pdf. Which in terms of PDF box means that I have to select images from page resources but when I am trying to do so with the built-in function `resources.getImages()` it is not working.
Please help.

P.S.: Thank you for this library.

**Comment by TomRoush** [comment]
`resources.getImages()` was deprecated and removed. Instead, use something like the code snippet below. Does that do what you need?
```
for (COSName name : resources.getXObjectNames()) {
    PDXObject xobj = resources.getXObject(name);
    if (xobj instanceof PDImageXObject)
    {
        Bitmap bit = ((PDImageXObject)xobj).getImage();
        // Do whatever with the image
    }
 }
```

**Comment by cannizarro** [comment]
Thanks for the response.
