### ISSUE TITLE
How can I make a PDDocument using a path to file in storage ?

### ISSUE THREAD

**Issue by cannizarro** [TomRoush/PdfBox-Android#187]

**Comment by TomRoush** [comment]
`PPDcoument.load()` can tale a `File` object as its parameter, which is what you would use for loading a document from storage. You can create a `File` from a String path if that's the input you have.

**Comment by cannizarro** [comment]
I figured it out. If you have a content Uri it won't be converted to file
path directly by 'getPath()' method. But you can convert it into an input
stream which can further be passed in place of File variable in
PDDocument.load(InputStream).

Thank You for responding.
