### ISSUE TITLE
InvalidPasswordException is never thrown

### ISSUE THREAD

**Issue by judeosbert** [TomRoush/PdfBox-Android#189]
When I try to detect if a pdf has password with 
`private void isPDFProtected(String destinationPath,String password) throws IOException {
        PDDocument pdfDocument = PDDocument.load(new File(destinationPath), password);
        pdfDocument.setAllSecurityToBeRemoved(true);
        pdfDocument.save(new File(destinationPath));
    }`
and I catch with 
` catch (IOException e) {
            e.printStackTrace();
            //Open Alert Dialog
            uiThread.post(new Runnable() {
                @Override
                public void run() {
                    openAlertForPassword(destinationPath,url);
                }
            });
        }`
As per docs the InvalidPasswordException should be thrown. I looked at the source and all load methods are throwing IOException. Is there something I am missing?

**Comment by THausherr** [comment]
InvalidPasswordException extends IOException. This is a javadoc issue, which is fixed in Apache PDFBox, where the InvalidPasswordException is mentioned separately.

**Comment by judeosbert** [comment]
Ohh okay, thanks for replying, Can you tell a workaround for this? Where I can get this Exception ??

**Comment by THausherr** [comment]
Try catching the exception like this:
```
try
{
     doc = PDDocument.load(....);
}
catch (InvalidPasswordException ipe)
{
    // wrong password
}
catch (IOException ioe)
{
    // other problem
}

```

**Comment by judeosbert** [comment]
I tried this , I think studio was showing me an error when I added InvalidPasswordException. I will definitely try this out again. Thanks

**Comment by THausherr** [comment]
Either you didn't import it, or I'm wrong and in that case you'd have to analyze the text of the IOException that you get. But InvalidPasswordException should be thrown, I looked in StandardSecurityHandler.java and it is thrown.

**Comment by judeosbert** [comment]
Thanks its working !!! 😄
