### ISSUE TITLE
java.io.IOException: No such file or directory when use  ut.mergeDocuments(true);

### ISSUE THREAD

**Issue by MomenZaq** [TomRoush/PdfBox-Android#190]
Hi,
I want to merge some files into one file.
When I use     `ut.mergeDocuments(false); `
Everything goes well, but I want to save more memory by using 
                        `    ut.mergeDocuments(true);`

I face this bug 
`java.io.IOException: No such file or directory 
`
in **RandomAccessBufferedFileInputStream** class
`File tmpFile = File.createTempFile(TMP_FILE_PREFIX, ".pdf")`

**Comment by THausherr** [comment]
Please include the full stack trace - does it mention a name?

Try also creating a temp file yourself with `File.createTempFile()` - does it work? I wonder if the temp directory is writeable. Please get the value of the "java.io.tmpdir" system property, then find out if it exists and is writeable.

**Comment by thekevinbrown** [comment]
We're seeing this issue presenting like this:

![Screenshot_20191101-105709](https://user-images.githubusercontent.com/1531750/67995100-da5aeb00-fc9c-11e9-9601-11dd20c4d26c.png)

I unfortunately don't have a stack trace as this is an end user experiencing this issue.

**Comment by THausherr** [comment]
First find out whether that directory exists at all, and whether you can create files there yourself. If no => that's the problem and not related to PDFBox. If yes, then it means there's a problem with RandomAccessBufferedFileInputStream, the best would be to test this one isolated, i.e. create one with an InputStream as parameter and see what happens.
