### ISSUE TITLE
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.

### ISSUE THREAD

**Issue by NirmalPrajapat** [TomRoush/PdfBox-Android#192]
I'm using PdfBox 1.8.10 in my android project. When I run the project it throws an error saying 
**Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.**

Please suggest me a possible solution for this problem.

**Comment by daminimehra28** [comment]
you are using the same library in Gradle or in the lib folder. and refer this link:[](https://stackoverflow.com/questions/49254785/apptransformdexarchivewithexternallibsdexmergerfordebug-in-android-studio-3-0-1)

**Comment by NirmalPrajapat** [comment]
Actually this error is not just by adding PdfBox 1.8.10 dependency, if I add `implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'com.jakewharton.rxbinding2:rxbinding:2.2.0'` these dependencies it is throwing same error.

**Comment by daminimehra28** [comment]
Then remove the unnecessary implemented library.
