### ISSUE TITLE
2.0.0+ Support

### ISSUE THREAD

**Issue by milouk** [TomRoush/PdfBox-Android#202]
Hey @TomRoush Great work you've done there mate.
Been building an app that signs pdf docs and appends validationInformation.
For that i need both ExternalSigningSupport andCOSName 2.0.8+

Are there any plans to update to 2.0.0+? 

(I tried building 2.0.0 from sources but i still miss the aforementioned)

**Comment by mani516** [comment]
Hey @milouk 
i too need the update for signing related features
May i know if you managed to do this somehow?

I was trying to use java examples from https://svn.apache.org/viewvc/pdfbox/trunk/examples/src/main/java/org/apache/pdfbox/examples/signature/

i tried to copy paste required classes to run the examples above in android app, but when i try to validate the signatures with some online tools, it is getting failed.

**Comment by milouk** [comment]
> Hey @milouk
> i too need the update for signing related features
> May i know if you managed to do this somehow?
> 
> I was trying to use java examples from https://svn.apache.org/viewvc/pdfbox/trunk/examples/src/main/java/org/apache/pdfbox/examples/signature/
> 
> i tried to copy paste required classes to run the examples above in android app, but when i try to validate the signatures with some online tools, it is getting failed.

Yes i have managed to make it work but haven't pushed my changes.  If you need so i can push it. (though its not android compatible, just java)

**Comment by mani516** [comment]
So you were not using it with an android app? If not for android compatibility, we could just use the actual apache pdfbox library itself right?

**Comment by milouk** [comment]
> So you were not using it with an android app? If not for android compatibility, we could just use the actual apache pdfbox library itself right?

On android i made the signing work but not the validation. All i care for is the validation otherwise signing would be useless. The validation libs were added in v2.0.0+ while the signing libs were added much earlier (in fact they are available in this repo here).

**Comment by mani516** [comment]
yes i understand
Have you tried pdf signing with private key stored in AndroidKeyStore? Can you share some code for demonstration of how it is done in android?

The problem i am facing is, even though i am able to sign in android, when i try to validate with online tools like https://global-rookery-867.appspot.com/#, https://account.ascertia.com/demos/PDFSignatureVerificationStep1 and even programmatically with android libraries like PSPDFKit, the verification was unsuccessful.

When i tried signing with pspdfkit android library, the verification was successful using the online tools mentioned above.

**Comment by milouk** [comment]
> yes i understand
> Have you tried pdf signing with private key stored in AndroidKeyStore? Can you share some code for demonstration of how it is done in android?
> 
> The problem i am facing is, even though i am able to sign in android, when i try to validate with online tools like https://global-rookery-867.appspot.com/#, https://account.ascertia.com/demos/PDFSignatureVerificationStep1 and even programmatically with android libraries like PSPDFKit, the verification was unsuccessful.
> 
> When i tried signing with pspdfkit android library, the verification was successful using the online tools mentioned above.

this is exactly what im saying. I think you are mistaking two things.

Signing indeed WORKS CORRECTLY. The fact that is not being validated by online tools is because probably you used a self signed certificate or a certificate whose root provider is not a valid provider.
That doesnt mean signing didnt work it means that Adobe or any other validator you used doesnt recognize the authority that provided the certificate.

**Comment by mani516** [comment]
For signing i used a certificate along with its chain (whose root certificate is a self signed certificate).

The same certificate is used with pdfbox and pspdfkit libraried. I understand the issue with verification in case of self signed certificates as the certificate will not be trusted by those tools. But in such case, those tools would atleast show signer information like name, date etc and then they say that the certificate is not trusted. this is happening if i sign with same certificate using pspdfkit library. But if the signing is done with pdfbox, then the tools are not showing signer info, even pspdfkit's verify apis returning `DigitalSignatureValidationResult{status=ERROR, problems=[CERTIFICATE_CHAIN_FAILURE, DOCUMENT_INTEGRITY_FAILURE], documentIntegrityStatus=FAILED_RETRIEVE_SIGNATURE_CONTENTS, certificateChainValidationStatus=FAILED_RETRIEVE_SIGNATURE_CONTENTS, certificateChainValidationErrorMessage='null'}`

**Comment by mani516** [comment]
But the pdfbox's signature verification apis are able to retrieve signer info from the signed document regardless of the library used for signing (pspdfkit vs pdfbox).

Anyways, i have found one issue with online tools: if i upload signed pdf (which was just generated from android app using pdfbox lib) from mobile phone memory to the browser running in my pc, signer info is not shown. But if i copy the signed pdf into pc storage and upload it to the tools, then the signer info is shown. Now the only issue is with pspdfkit library apis.

Thanks for your time @milouk

**Comment by 4brunu** [comment]
For those interested there is this fork https://github.com/m-awadi/PdfBox-Android that upgraded the PdfBox to version 2.0.18, but I'm not sure if it's stable.
