### ISSUE TITLE
load pdf file very slow

### ISSUE THREAD

**Issue by ngochai84** [TomRoush/PdfBox-Android#203]
Hi @TomRoush ,
I like your library, but when trying with 9MB pdf (attached), it take long time whn run to PDDocument.load...

[FoEE 1 and 2_8367367b7e0812f7ad1af7fc1350a415.pdf](https://github.com/TomRoush/PdfBox-Android/files/3879817/FoEE.1.and.2_8367367b7e0812f7ad1af7fc1350a415.pdf)

**Comment by ngochai84** [comment]
@TomRoush , I can make thi library can load the attached file within some seconds instead of some minutes, let me test more and give for you a pull request

**Comment by KnIfER** [comment]
It takes ~10sec to load Gray's Anatomy (4th, 225mb)  
Then I tried the latest PDFBox (v2.0.17) on the PC; It's even worse! It will take 17 secs !
I would say there're still a lot of works to be done...

**Comment by pranayzv** [comment]
Try using thread to get data before its needed.
you have to design an algorithm for when you want/need the data.
hope it helps!

**Comment by TomRoush** [comment]
I saw a dramatic decrease in loading time when using your changes. Thanks for contributing.
