### ISSUE TITLE
How to check isPDF is protected or not

### ISSUE THREAD

**Issue by MustafaDev-shaikh** [TomRoush/PdfBox-Android#217]
It is possible to check that PDF is protected. If is protected than User have to enter password.How can we do this..

**Comment by Ragulsekar** [comment]
@MustafaDev-shaikh Did you get solution to open password protected PDF? I am also looking solution for this.

**Comment by MustafaDev-shaikh** [comment]
@Ragulsekar  yes I have solve the solution after load PDF file in  **PDDocument**

 ` PDDocument document = PDDocument.load(new File(RealPathUtil.getRealPath(this, mediaFiles.get(i).getUri())));`

if pdf file is protected it will catch in **IOException** and same loop run and you can check isPasswordCorrect or wrong

**Comment by Ragulsekar** [comment]
@MustafaDev-shaikh As you said protected pdf file is catch in IOException, here how can I enter the pdf password and open it. Do you have code for open protected pdf file? It will be helpful for me, thanks in advance.

**Comment by MustafaDev-shaikh** [comment]
@Ragulsekar yes you can check this code after unlock pdf u can use library 

`  @SuppressLint("SetTextI18n")
    private void openDialog(int i, Uri uri, String name) {
        final AlertDialog dialogBuilder = new AlertDialog.Builder(this).create();
        LayoutInflater inflater = this.getLayoutInflater();
        @SuppressLint("InflateParams") View dialogView = inflater.inflate(R.layout.pop_up_password, null);

        final EditText editText = dialogView.findViewById(R.id.edt_comment);
        final TextView textView = dialogView.findViewById(R.id.textView);
        Button button1 = dialogView.findViewById(R.id.button3);
        Button button2 = dialogView.findViewById(R.id.button4);

        textView.setText("Enter Password For : " + name);
        button2.setOnClickListener(view -> {
            userPass = editText.getText().toString().trim();

            if (userPass.isEmpty()) {
                editText.setError("enter password");
                editText.requestFocus();
            } else {
                try {
                    PDDocument document = PDDocument.load(new File(RealPathUtil.getRealPath(DocumentUpload.this, mediaFiles.get(i).getUri())), userPass);
                    //   PDDocument document = PDDocument.load(new File(RealPathUtil.getRealPath(DocumentUpload.this, mediaFiles.get(i).getUri())), userPass);
                    Toast.makeText(DocumentUpload.this, "Successfully unlock", Toast.LENGTH_SHORT).show();
                    FileModel fileModel = new FileModel(""
                            , "local", uri, "pending", null, userPass, false);
                    fileModels.add(fileModel);
                    docGroup.get(docGroupPos).getDocSet().get(docSetPosDisable).setPicked(true);
                    documentGroupAdapter.notifyDataSetChanged();

                    Log.d(TAG, "subcategory_id: " + docGroup.get(docGroupPos).getDocSubcategoryId());
                    Log.d(TAG, "doc_defination_id: " + docGroup.get(docGroupPos).getDocSet().get(docSetPosDisable).getDocDefination().get(docDefinationPos).getId());
                    userPass = null;
                    dialogBuilder.dismiss();
                } catch (IOException ex) {
                    ex.printStackTrace();
                    Toast.makeText(DocumentUpload.this, "Wrong password", Toast.LENGTH_SHORT).show();
                }

            }
        });
        button1.setOnClickListener(view -> {
            // DO SOMETHINGS
            userPass = null;
            docGroup.get(docGroupPos).getDocSet().get(docSetPosDisable).setPicked(false);
            documentGroupAdapter.notifyDataSetChanged();
            dialogBuilder.dismiss();
        });
        dialogBuilder.setCancelable(false);
        dialogBuilder.setView(dialogView);
        dialogBuilder.show();
    }`
