### ISSUE TITLE
JPEGfactory related question 

### ISSUE THREAD

**Issue by jayantur13** [TomRoush/PdfBox-Android#227]
Hello, this library is very helpful,but I am stuck.. Need help and clarifications.

public static PDImageXObject createFromImage(PDDocument document, Bitmap image,
        float quality, int dpi) throws IOException
    {
        return createJPEG(document, image, quality, dpi);
    }

1) For quality when I put 0 or 100 it works,but other values give me java.lang.IllegalArgumentException: quality must be 0..100
2) Perfect values for dpi

**Comment by maxakash** [comment]
The image quality should be between 0 to 1 as the inside the method it is multiplied by 100.

The value of dpi is not used, so you can use any dpi

**Comment by jayantur13** [comment]
Thank you @maxakash, I tried the same and for dpi 72 it works. My purpose to decrease image quality and pdf size is fulfilled.
