### ISSUE TITLE
Is WRITE_EXTERNAL_STORAGE required in the manifest?

### ISSUE THREAD

**Issue by sampengilly** [TomRoush/PdfBox-Android#230]
I've just been converting an app to be instant-enabled. As part of that I removed the WRITE_EXTERNAL_STORAGE permission from the app and removed code that required the permission. After publishing to an internal test track I was surprised to see that the permissions still listed external storage read/write permissions. Tracing it through the merged manifest I see that the write permission is being added here.

I've done a cursory search through the repository, I can't seem to find anything that's referencing "external" files. There was also an issue around setting up runtime permissions not long ago. Is the explicit manifest permission still required? Is there anything that PDFBox does internally that requires external storage or is it completely agnostic of the storage location? I would like to be sure as instant apps do not allow access to external storage.

**Comment by TomRoush** [comment]
I will double check, but I don't believe it is necessary and it can be removed
