### ISSUE TITLE
PDAppearanceEntry.isStream() on a null object reference

### ISSUE THREAD

**Issue by gibranhit** [TomRoush/PdfBox-Android#235]
when I try to open a pdf and I get the object to insert the value inside the pdftextfield it returns a null in the PDAppearanceEntry.
![Captura de Pantalla 2020-12-07 a la(s) 18 08 27](https://user-images.githubusercontent.com/24420823/101420174-3daf4780-38b7-11eb-87d8-787f0a400cc4.png)
isStream()

**Comment by TomRoush** [comment]
Resolved in 2.0.0.0+
