### ISSUE TITLE
[Feature Request] Support for Base64 data

### ISSUE THREAD

**Issue by DreamzUpAbove** [TomRoush/PdfBox-Android#241]
Hey Tom.. 

**That's an awesome work so far completed.** 

I have a small feature enhancement request, to include _Base64 support_ as it is the easy and universal format of client-server communication for file transfers.

My requirement was to save an Base64 PDF file generated at server at Android. I have managed to do the same at my end. If you're busy, I can open a Pull request with my changes.

@TomRoush  Cheers...

**Comment by TomRoush** [comment]
Glad to hear that this library helped you. As this feature isn't present in the desktop PDFBox version, I think that it would be better left to the library's users or another library
