### ISSUE TITLE
Migrate away from JCenter

### ISSUE THREAD

**Issue by ligol** [TomRoush/PdfBox-Android#243]
JFrog has just announced that it will be shutting down JCenter on May 1st. JCenter is the sole repository hosting this library, so it will become unavailable after this date unless migrated to an alternative service. Could it be migrated to mavenCentral to remains usable in gradle?

https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by 4brunu** [comment]
I also have this issue.
@TomRoush could you please help with this?
Thanks

**Comment by 4brunu** [comment]
I found this PR on the ReLinker repo, which shows the migration from jcenter to MavenCentral, so I put it here for reference, in case it helps with the migration.
https://github.com/KeepSafe/ReLinker/pull/81

**Comment by 4brunu** [comment]
@TomRoush would it be possible to also publish the last stable release 1.8.10.3 on maven central?
Thanks

**Comment by TomRoush** [comment]
@4brunu Done. The first release might take some time to be synced to Maven Central. The artifact coordinate is `com.tom-roush:pdfbox-android:1.8.10.3`. Note that the groupId has been changed

**Comment by 4brunu** [comment]
@TomRoush thanks 👍
