### ISSUE TITLE
PdfBox-Android working on old version of Apache PDFBox

### ISSUE THREAD

**Issue by KavinAgrawal** [TomRoush/PdfBox-Android#263]
@TomRoush Why the library is dependent on older versions of the PDFBox 1.8.10? Is there some specific reason for not using latest version of apache PDFBox 3.0.0-RC1 or 2.0.23?

**Comment by KavinAgrawal** [comment]
@TomRoush Any answer?

**Comment by TomRoush** [comment]
Work is being done to upgrade to 2.0, but it will take some time to upgrade to the latest version. 3.0 work wouldn't be considered until the final 3.0.0 release is out

**Comment by DartPads** [comment]
Thank you for your hard work. I really appreciate your time. Is there an approximate ETA for when we might reach 2.0.10. Thanks again.

**Comment by TomRoush** [comment]
Closing this issue. Tentative release dates for all API releases are listed under milestones: https://github.com/TomRoush/PdfBox-Android/milestones
