### ISSUE TITLE
How understand if text will fit in page ?

### ISSUE THREAD

**Issue by albertocappellina** [TomRoush/PdfBox-Android#272]
Hi, 

  is there a way to see if text will fit in page ? Eg. if text is too long i have to break it down to 2-3 text or insert new line in right poiint.

Are there any function to see the rect of the text i will be rendering?

Thanks!
Alberto

**Comment by TomRoush** [comment]
Does something like this: [Apache PDFBox adding multiline paragraph](https://memorynotfound.com/apache-pdfbox-adding-multiline-paragraph/) do what you need?

**Comment by albertocappellina** [comment]
yes! thanks you so much! 

i also used font.getStringWidth(...)  to get dimension of text
