### ISSUE TITLE
Multiple acro form fields filling issue

### ISSUE THREAD

**Issue by wildman12** [TomRoush/PdfBox-Android#280]
Hi, thank you for this library :)

I'm using the library to fill the acro PDF form. But I encountered an issue very similar to #169 

I want to fill several form fields and show using renderer. But I'm only able to see single value(first one entered).
Here's example test code:
```Kotlin
    private fun test() {
        fillField(0)
        fillField(1)
        fillField(2)
        fillField(3)

        renderDoc()
    }

    private fun fillField(fieldPosition: Int) {
        val pdTextField = fields[fieldPosition] as PDTextField
        pdTextField.value = "Test value"
    }
```

In this case I will see only form filled with index 0.
In case I comment out this line:
```Kotlin
    private fun test() {
        //fillField(0)
        fillField(1)
        fillField(2)
        fillField(3)

        renderDoc()
    }
```

Form filled with index 1 will be rendered correctly etc.

I can see that in `PDFStreamEngine#processAnnotation` annotation does contain the text values for all fields.

This feels like a big issue and not sure it could've been missed so maybe I'm doing something wrong. Any suggestion would be appreciated.

**Comment by wildman12** [comment]
Issue is with `canvas.clipPath` in `PageDrawer`:
```java
private void setClip()
    {
        Region clippingPath = getGraphicsState().getCurrentClippingPath();
        if (clippingPath != lastClip)
        {
            canvas.clipPath(clippingPath.getBoundaryPath());
            lastClip = clippingPath;
        }
    }
```

Removing it solves the issue but probably causes some performance drop?

**Comment by TomRoush** [comment]
Good find. I think it would cause other rendering issues. I remember removing it at one point because I suspected it might have caused some other rendering issues, but I put it back because it didn't seem to change anything
