### ISSUE TITLE
Conversion PDF image display incomplete

### ISSUE THREAD

**Issue by bichao1986** [TomRoush/PdfBox-Android#292]
In the process of converting PDF files to pictures, I found that if the PDF file contains a large number of pictures, the pictures after the conversion are not displayed completely, and the pictures in the PDF file are not converted successfully
I upload two PDF files for testing
[https://oss.littlehotspot.com/forscreen/resource/7121253942add92e4f9cf89f207e1f11.pdf](url)
[https://oss.littlehotspot.com/forscreen/resource/7ba8e79abbea5f7620d9a4ff77f02c67.pdf](url)
I hope to get your help，Thanks!!!

**Comment by TomRoush** [comment]
By converting PDF files to images, I assume you mean using `PDFRenderer.renderImage()`?

In the first PDF, some of the images and text aren't rendering because the color spaces aren't supported yet. Specifically ICC Based colorspaces are not yet supported

In the second PDF, I didn't notice any issues. Could you share the code you used or a specific example of a problem that you're seeing?

**Comment by bichao1986** [comment]
Thank you for your reply。
I use this method PDFRenderer.renderImage()。
Here is the code I used：
public void renderFile(View v) {
        // Render the page and save it to an image file
        FileOutputStream fileOut = null;
        try {
            // Load in an already created PDF
            PDDocument document = PDDocument.load(assetManager.open("MMDLIS1.0.pdf"));
            // Create a renderer for the document
            PDFRenderer renderer = new PDFRenderer(document);
            // Render the image to an RGB Bitmap
//            pageImage = renderer.renderImage(0, 1, ImageType.ARGB);
            int pages = document.getNumberOfPages();
            for (int i=0;i<pages;i++){
                pageImage = renderer.renderImage(i, 1, ImageType.ARGB);

                // Save the render result to an image
                String path = root.getAbsolutePath() + "/"+i+".jpg";
                File renderFile = new File(path);
                fileOut = new FileOutputStream(renderFile);
                pageImage.compress(Bitmap.CompressFormat.JPEG, 100, fileOut);
                tv.setText("Successfully rendered image to " + path);
            }
        }
        catch (IOException e)
        {
            Log.e("PdfBox-Android-Sample", "Exception thrown while rendering file", e);
        }finally {
            if (fileOut!=null){
                try{
                    fileOut.close();
                }catch (Exception e){
                    e.printStackTrace();
                }
            }
        }
    }

Will the first PDF file support that in the future?

About the second PDF file, I found that the background color of the picture turned black after conversion，I use the development library, not the tag version
![0 1](![1 1](https://user-images.githubusercontent.com/11400852/127297270-7c6869e3-0d15-40d4-8377-ddb831d0cba0.jpg))

**Comment by TomRoush** [comment]
For the first PDF, yes it will be supported but I don't have an estimate on when.
For the second PDF. try changing the image type to `ImageType.RGB`, that should give you a white background. I'll have to look into if there's a problem with ARGB. I think ARGB should have also given you a white background

**Comment by bichao1986** [comment]
ok，Thanks，Looking forward to further optimization
