### ISSUE TITLE
Digital signature without ExternalSigningSupport

### ISSUE THREAD

**Issue by ReDeLSiLeNziO** [TomRoush/PdfBox-Android#300]
Hello,
I'm trying  to make a digital signature on PDFs, but i've difficult to use the same flow of pdf box for desktop, beacause  ExternalSigningSupport is not present in v2.0.0 

Could I have a simple snippet of code sample in order to use the alternative of
`ExternalSigningSupport externalSigning = document.saveIncrementalForExternalSigning(output);
externalSigning.getContent()`

Thank you so much!

**Comment by TomRoush** [comment]
Have you looked at the desktop examples yet: https://github.com/apache/pdfbox/tree/2.0.1/examples/src/main/java/org/apache/pdfbox/examples/signature

If you can wait a bit, ExternalSigningSupport is scheduled to be in snapshots sometime next and should be released towards the end of the month

**Comment by ReDeLSiLeNziO** [comment]
Hello Tom,
ok, thank you! I'll wait for 2.0.1 at the end of the month.

Thanks for your work!

**Comment by TomRoush** [comment]
ExternalSigningSupport has been added

**Comment by ReDeLSiLeNziO** [comment]
thanks!
