### ISSUE TITLE
Annotations showing

### ISSUE THREAD

**Issue by naintrakusam** [TomRoush/PdfBox-Android#319]
Hi, as stated in pdfbox documentation, to ensure that annotations will be visible in all viewers, one should call this after adding annotation to the page's annotation list, before saving the document :

_**annotations.forEach(ann -> ann.constructAppearances(document));**_

But in your current release, _**constructAppearances**_ is still missing. Do you think it can be added in near feature ?

_"Since 2.0.16 the appearance stream of many annotation types can be created with annotation.constructAppearances(). – 
Tilman Hausherr
 Aug 13 '19 at 9:32"_

- [ ] Feature not yet ported to PdfBox-Android

Thanks

**Comment by TomRoush** [comment]
It doesn't look like there are any difficult changes, so I can see about getting this added sooner. Is constructAppearances() the only function that you're missing? Are you looking render those PDFs using PdfBox-Android as well?

**Comment by naintrakusam** [comment]
Yes, I would like to use PDFBOX as complex PDF viewer and also annotation editor. 
Im not really sure if adding constructAppearances() is enough to render annotations with pdfbox, but it seems to be good start point at least (according examples). Thanks for your response, looking forward to get the build ;)
