### ISSUE TITLE
using an unusigned array w/o checking at setStroke(...)

### ISSUE THREAD

**Issue by 312937** [TomRoush/PdfBox-Android#354]
**Describe the bug**
null pointer exception

**To reproduce**
single line remedy described as 'additional context'

**PDF example**
single line remedy described as 'additional context'

**Expected behavior**
checking object/array at setStroke(...)

**Actual behavior**
using object/array w/o checking at setStroke(...)

**Environment details:**
 - PdfBox-Android version: [e.g. 2.0.12.0] PdfBox >= 2.0.8.0
 - Android API version: [e.g. API 31] no matter

**Additional context**
REMEDY (simplified, obvious diff)
```
  .../library/src/main/java/com/tom_roush/pdfbox/rendering/PageDrawer.java
  @@ -1094,7 +1094,10 @@ public class PageDrawer extends PDFGraphicsStreamEngine
         p.setStrokeCap(cap);
         p.setStrokeJoin(join);
         p.setStrokeMiter(miterLimit);
  -        p.setPathEffect(new DashPathEffect(dash, dash_phase));
  +        if (dash != null)
  +        {
  +            p.setPathEffect(new DashPathEffect(dash, dash_phase));
  +        }
       }

```

**Comment by TomRoush** [comment]
Looks good. If you'd like to, feel free to create a PR and I'll approve. Otherwise I'll create one and get it in before the next release
