### ISSUE TITLE
Parse document dynamically

### ISSUE THREAD

**Issue by DominikKu** [TomRoush/PdfBox-Android#365]
Hi
I would like to ask if it is possible to parse a document page by page. Right now I'm using PDDocument.load in my pdf file (30MB, 700 pages) but it takes more than a minute. The problem is, I can't take any page without parsing the full pdf file.

**Comment by TomRoush** [comment]
Unfortunately, parsing out a single page isn't supported. I haven't done much performance testing, but you can try using `loadNonSeq` instead of `load` which may improve your load times

**Comment by dayang123** [comment]
> Unfortunately, parsing out a single page isn't supported. I haven't done much performance testing, but you can try using `loadNonSeq` instead of `load` which may improve your load times

How to use loadNonSeq ?     PDDocument.loadNonSeq ()?   There is not this method  in 2.0.24.0

**Comment by TomRoush** [comment]
`loadNonSeq` has been removed, and the performance improvements have been worked into the normal `load` method, so you should be using that in 2.0.24.0
