### ISSUE TITLE
Apk size very large after rebuild in Release mode?

### ISSUE THREAD

**Issue by vimalcvs** [TomRoush/PdfBox-Android#407]
**How to remove unnecessary font?**

**Environment details:**
 - PdfBox-Android version: [e.g. 2.0.21.0]
 - Android API version: [e.g. API 31]

**Additional context**
![alt text](https://technovimal.in/apps/test/upload/1653152237_size.png)

**Comment by TomRoush** [comment]
If you're not using the font and want to remove if you can safely remove it from your APK. For example, adding this to your app's build.gradle will remove it:
``` gradle
android {
    aaptOptions {
        ignoreAssetsPattern "!*LiberationSans-Regular.ttf"
    }
}
```
