### ISSUE TITLE
Read pdf too long/out of memory -  caused by read lookup table is not supported 

### ISSUE THREAD

**Issue by ngochai84** [TomRoush/PdfBox-Android#410]
**Describe the bug**
use this file to try open and add more content 
[pdf_background_2022-02-19-071145.pdf](https://github.com/TomRoush/PdfBox-Android/files/8767686/pdf_background_2022-02-19-071145.pdf)

Android device will be out off memory after long time loading

on the trace log I see **Type X GSUB lookup table is not supported and will be ignored** (x = 4, 5 , 6, ... etc)

**Comment by TomRoush** [comment]
What version are you using and what are the specs of the device you're having this problem on? I was able to load the PDF in <1 second using the latest version of the library on my test devices.

The "GSUB lookup table" messages are font related, and expected for this PDF.

**Comment by ngochai84** [comment]
I'm running on android 12  and let me try to upgrade the library with version 2.0.22 (i'm using version 2.0.20 as I remember)

**Comment by ngochai84** [comment]
solved
