### ISSUE TITLE
How to determine whether the origin of coordinates of a page is the top left vertex or the bottom left vertex？

### ISSUE THREAD

**Issue by GodTreeV** [TomRoush/PdfBox-Android#471]
description：
When I save an image to the first page using the following method, the origin of its coordinate system is not the top left vertex, but the bottom left vertex
![image](https://user-images.githubusercontent.com/42767951/210304148-f98c91f7-3fe3-47f2-ba5d-38e2b4d00c64.png)

**Comment by TomRoush** [comment]
Yes, that's by design. The origin of a PDF is at the bottom left. Here's an explanation with a little more detail: https://www.pdfscripting.com/public/PDF-Page-Coordinates.cfm

**Comment by GodTreeV** [comment]
> Yes, that's by design. The origin of a PDF is at the bottom left. Here's an explanation with a little more detail: https://www.pdfscripting.com/public/PDF-Page-Coordinates.cfm

Tanks a lot.In other words, if I use page to get the rotation Angle of a certain page, if it is rotated 180 degrees, please tell me whether it is the center rotation or based on which point

**Comment by TomRoush** [comment]
The page rotation is applied after everything has been placed on the page, so you don't have to worry about how the coordinates work with rotation
