### ISSUE TITLE
VerifyError when creating PDImageXObject

### ISSUE THREAD

**Issue by szymanskip** [TomRoush/PdfBox-Android#55]
I get this error:

    java.lang.VerifyError: org/apache/pdfbox/pdmodel/graphics/image/PDImageXObject
            at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createFromStream(JPEGFactory.java:46)

when I am trying to create PDIMageXObject

    PDImageXObject pdImage = JPEGFactory.createFromStream(document, new FileInputStream(new File(path)));

I get this error on device and emulator but only when running on API 15

I am using latest version of PdfBox-Android 1.8.9.0

Just checked: I dont get an Exception when using JAR version 1.8.7 of PdfBox-Android, but this version have a problem with loading resources  #32 

RESOLVED:
I cloned repository and compiled library to AAR and it works fine on API15 now. I compiled using latest build-tools 23.0.1, perhaps that was the reason.

**Comment by TomRoush** [comment]
Thanks for letting me know. I've updated the gradle files in case anyone else runs into this issue.

**Comment by uugan** [comment]
PDPage page = doc.getDocumentCatalog().getPages().get(0);
                        File phone = new File(downloadFolder + File.separator + "image.jpg");
                        FileInputStream mInput = new FileInputStream(phone);
                        PDImageXObject img = JPEGFactory.createFromStream(doc, mInput);

API 15 still gives error below:
java.lang.VerifyError: org/apache/pdfbox/pdmodel/graphics/image/PDImageXObject
    at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createFromStream(JPEGFactory.java:46)
