### ISSUE TITLE
How to get all positions of specific term in PDF

### ISSUE THREAD

**Issue by MathieuH11** [TomRoush/PdfBox-Android#57]
I'd like to get all the TextPosition of a term. Is this possible ? 
This will be used to implement a "search term" functionnality in a project. 
Then with these positions, I'll highlight the text with the coordinnates.
Thaks a lot.

**Comment by TomRoush** [comment]
I haven't tested it, but something like [this example](https://jackson-brain.com/using-pdfbox-to-locate-text-coordinates-within-a-pdf-in-java/) should help you get started. You'll basically being extending the PdfTextStripper class to get the information that you need.

**Comment by MathieuH11** [comment]
Ok, thank you.
