### ISSUE TITLE
Can't get showText() to work (font exceptions)

### ISSUE THREAD

**Issue by gnug** [TomRoush/PdfBox-Android#58]
(Working on Android 4.3, Android Studio 1.4, please ask if you need more info)

I can't get writing text to work, which seems to be related to font problems. Using a version of the library from earlier this year (a co-worker included a copy of the .jar file in the project at that time), I used to get errors of the following kind when calling PDPageContentStream.showText():

     "java.lang.IllegalArgumentException: No glyph for U+0053 in font Times-Bold"

The font I used here was PDType1Font.TIMES_BOLD.

I've given up on that version and added the recommended build.gradle dependency instead:

     compile 'org.apache:pdfbox-android:1.8.9.0'

But now the showText() call crashes with a null pointer exception (I'm using TIMES_ROMAN now if it makes a difference - I guess that it doesn't):

    10-15 01:07:52.213 13986-13986/com.ems.test W/System.err: java.lang.NullPointerException
    10-15 01:07:52.221 13986-13986/com.ems.test W/System.err:     at org.apache.pdfbox.pdmodel.font.PDType1Font.getNameInFont(PDType1Font.java:422)
    10-15 01:07:52.221 13986-13986/com.ems.test W/System.err:     at org.apache.pdfbox.pdmodel.font.PDType1Font.encode(PDType1Font.java:285)
    10-15 01:07:52.221 13986-13986/com.ems.test W/System.err:     at org.apache.pdfbox.pdmodel.font.PDFont.encode(PDFont.java:249)
    10-15 01:07:52.221 13986-13986/com.ems.test W/System.err:     at org.apache.pdfbox.pdmodel.PDPageContentStream.showText(PDPageContentStream.java:292)

For your reference, here is an excerpt from my code:

        PDDocument document = new PDDocument();
        PDPageContentStream contentStream;
        PDPage titlePage = new PDPage(PDRectangle.A4);
        document.addPage(titlePage);
        PDPage page = new PDPage(PDRectangle.A4);
        document.addPage(page);
        contentStream = new PDPageContentStream(document, page);
        PDRectangle rect = page.getMediaBox();
        PDFont fontPlain = PDType1Font.TIMES_ROMAN; 

        contentStream.beginText();
        contentStream.setFont(fontPlain, 12);
        contentStream.newLineAtOffset(rect.getWidth() / 2, 20);
        contentStream.showText("S");    <---------- this crashes
        contentStream.endText();

Is there any other information I need to get the library to work? Or does it work in principle but I have to limit myself to certain fonts, and if so, which ones and how do I select them? Perhaps you could just point me to an example that works? I couldn't find any, and the documentation seems to be rather sparse.

Thanks a lot for your time

**Comment by TomRoush** [comment]
Everything you've done so far looks correct, so I'm guessing that the problem is with the Times Roman font. If you use another standard font or load a custom font from file your code should work as expected. Times Roman has given warning about not being able to find a fallback font for a while now, this is most likely the same issue.

**Comment by TomRoush** [comment]
The issue is mostly fixed. The PDF itself is created properly, but the builtin Android fonts don't have a standard font similar to Times Roman, so if you render the page the font will be wrong.
