### ISSUE TITLE
PDDocument.save(file) is very slow

### ISSUE THREAD

**Issue by XavierLOTJ** [TomRoush/PdfBox-Android#59]
Using PDFBox-Android, I'm currently loading my PDF into a PDDocument like so:

```
PDDocument pdDoc = PDDocument.load(file);
PDDocumentCatalog pdCatalog = pdDoc.getDocumentCatalog();
PDAcroForm acroForm = pdCatalog.getAcroForm();
```

Then I am timing the save() function like this:

```
long substart = System.currentTimeMillis();
pdDoc.save(file);
Log.d("formData", "save took " + (System.currentTimeMillis() - substart) / 1000);
```

The save method is taking up to 10 seconds on a Nextbook NXA8QC116R (~6-7 seconds on my HTC One M8 And Lenovo Tab 2 A8) to save a PDF file that is only 93kb in size. I've also tried using a BufferedOutputStream to save the file, but that didn't seem to help.

Is this a flaw in the library, or is there something that I can do to help speed up the saving method for small files?

**Comment by TomRoush** [comment]
Definitely a flaw in the library. It looks like the issue might only affect PDFs with forms though.

**Comment by TomRoush** [comment]
Closing issue, saves consistently take <1 second across devices.
