### ISSUE TITLE
How to generate jar file for the eclipse project

### ISSUE THREAD

**Issue by Dharmendra10** [TomRoush/PdfBox-Android#60]
Hi,

I am trying to build the android project using the ./gradlew command in the android studio and it is generating jar files but this jar file contains java files instead of class files so when I am adding this jar files into eclipse its not working.

Please guide me to resolve this problem.

Thanks

**Comment by TomRoush** [comment]
There's three parts you need to make this work: the compiled source files, the assets, and the dependency libraries. The assets and compiled classes can be pulled from the aar file. You can build your own using gradle or download the precompiled one [here.](https://bintray.com/birdbrain2/PdfBox-Android/PdfBox-Android/view) Add the classes.jar to your build path and put the contents of the asset folder into your project's assets folder. You'll also probably need to download [these Spongy Castle libraries: core, prov, and pkiv.](https://rtyley.github.io/spongycastle/) Currently this library uses v1.51, though it looks like there are newer releases.

**Comment by Dharmendra10** [comment]
Hi Tom,

Thanks for your help. 
I pulled assets and classes.jar file into my eclipse project and now I am able to build the project and able to generate the pdf.

You saved my lots of time. Thank you very much.

**Comment by TomRoush** [comment]
No problem. I'm glad its working.
