### ISSUE TITLE
Problem with method renderImage(int page);

### ISSUE THREAD

**Issue by imsnow** [TomRoush/PdfBox-Android#61]
I've got this stacktrace
<code>
java.io.IOException: Invalid color space kind: COSName{Separation}
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.pdmodel.graphics.color.PDColorSpace.create(PDColorSpace.java:119)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.pdmodel.PDResources.getColorSpace(PDResources.java:88)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.contentstream.operator.color.SetNonStrokingColorSpace.process(SetNonStrokingColorSpace.java:41)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:802)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:464)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:438)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:147)
11-13 09:42:31.806 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:118)
11-13 09:42:31.811 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.rendering.PDFRenderer.renderPage(PDFRenderer.java:124)
11-13 09:42:31.811 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:87)
11-13 09:42:31.811 32169-32169/com.example.mike.pdfview W/System.err:     at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:43)
11-13 09:42:31.811 32169-32169/com.example.mike.pdfview W/System.err:     at com.example.mike.pdfview.PDFBoxAdapter.convertBitmap(PDFBoxAdapter.java:51)
11-13 09:42:31.811 32169-32169/com.example.mike.pdfview W/System.err:     at com.example.mike.pdfview.PDFBoxAdapter.getView(PDFBoxAdapter.java:87)
</code>

I recieve this part of the stacktrace six times. That's number of pages in my pdf document.
I  tried to render diffrent documents, but result is the same.

**Comment by RankoR** [comment]
Got the same error for every page in my document, but with different color space: "Invalid color space kind: COSName{ICCBased}"
Any progress?

**Comment by TomRoush** [comment]
I haven't had a chance to work on the colorspaces much at, so there's no progress yet.

**Comment by imsnow** [comment]
Tom, no problem

**Comment by ThePaulrBear** [comment]
This bug blocks four out five test PDFs I use from opening. For example when I try to open [this pdf](https://github.com/TomRoush/PdfBox-Android/files/402268/adobe_test.pdf) I get the following error:
`W/System.err: java.io.IOException: Invalid color space kind: COSName{ICCBased}`

Is there a workaround for this or a chance of a fix in the near future? My program will only open PDFs that we create ourselves, so if there is a way to avoid this error by using specific settings in creating the PDFs, that would work for me.

**Comment by TomRoush** [comment]
Yes, there is a workaround. PDFs created with the RGB colorspace should be fully supported. In Acrobat, you can go to Tools->Print Production->Convert Colors and set the conversion profile to an RGB one to get your PDFs to work properly.

**Comment by ThePaulrBear** [comment]
Thank you!

**Comment by Armenm** [comment]
Hi @TomRoush 
I have the same problem when creating pdf on iOS and showing it on Android.
PdfBoxAndroid: Invalid color space kind: COSName{ICCBased}
I would be grateful if you could help me to fix this, cause it blocks me completely.

**Comment by TomRoush** [comment]
Unfortunately, it isn't an easy fix. If you have control over the PDFs you're getting out of iOS, you can try a similar workaround to the one above. Otherwise, I'll work on a fix, but it may take some time to get done.

**Comment by kmichalak23** [comment]
Hello, I am receiving the same error as @Armenm. I was able to overcome it by forcing a specific COSName value to be used in the error case. However, when the image is rendered, some letters are redacted throughout the document. Is this a licensing issue? I noticed the same thing happened with documents that didn't throw this error. 

Thanks in advance!

**Comment by TomRoush** [comment]
ICCBased should be working with this workaround now. I'm not sure about the other colorspaces, I don't have test PDFs for those yet. Thanks for finding this solution @kmichalak23. As for your font problems, I fairly sure that they aren't related to this issue. If you are still having problems, create a new issue and share a problem PDF if possible.
