### ISSUE TITLE
java.lang.VerifyError: org/apache/pdfbox/pdmodel/graphics/image/PDImageXObject

### ISSUE THREAD

**Issue by uugan** [TomRoush/PdfBox-Android#63]
PDPage page = doc.getDocumentCatalog().getPages().get(0);
File phone = new File(downloadFolder + File.separator + "image.jpg");
FileInputStream mInput = new FileInputStream(phone);
PDImageXObject img = JPEGFactory.createFromStream(doc, mInput);

compileSdkVersion 23
android:minSdkVersion="15"
buildToolsVersion "23.0.2"
But still gives error below:
java.lang.VerifyError: org/apache/pdfbox/pdmodel/graphics/image/PDImageXObject
at org.apache.pdfbox.pdmodel.graphics.image.JPEGFactory.createFromStream(JPEGFactory.java:46)

**Comment by TomRoush** [comment]
I haven't been able to reproduce this, but I'll keep trying. Issue #55 was the same problem. Are you building from the source or getting the version from the jCenter repository?

**Comment by uugan** [comment]
from rep
