### ISSUE TITLE
adding page text overlay problem

### ISSUE THREAD

**Issue by partoutatis** [TomRoush/PdfBox-Android#65]
Hello !
Using PDFBox-Android, pdfbox-android:1.8.9.0 ; loading existing PDF to add text.

Problem is when create new pages, it use last page which contain previous text...

	private File writeReport() {
    	File fileSource = new File(getActivity().getApplicationContext().getExternalCacheDir(), "fileSource.pdf");

		// get file model in assets
        InputStream inputAsset = null;
        try {
            inputAsset = getActivity().getApplicationContext().getResources().getAssets().open("file_model.pdf");
        } catch (IOException e) {
            e.printStackTrace();
        }

        // copy file model in fileSource
        try {
            OutputStream outputStream = new FileOutputStream(file);
            byte buffer[] = new byte[1024];
            int length = 0;

            while ((length = inputAsset.read(buffer)) > 0) {
                outputStream.write(buffer, 0, length);
            }
            outputStream.close();
            inputAsset.close();
        } catch (IOException e) {
            System.out.print("Copy assets : IOException" + e.getMessage());
        }

        File fileTarget = new File(getActivity().getApplicationContext().getCacheDir(), "fileTarget.pdf");

        try {
            PDFBoxResourceLoader.init(getActivity().getApplicationContext());       // init lib

            PDDocument documentSource = PDDocument.load(fileSource);
            PDDocument documentTarget = new PDDocument();

            // iteration == a new page
            for(int i=0 ; i < 3 ; i++)
            {
                PDPage page = documentSource.getDocumentCatalog().getPages().get(0);
                PDPageContentStream contentStream = new PDPageContentStream(documentSource, page, true, true);

                PDFont font1 = PDType1Font.HELVETICA;

                float startY = page.getMediaBox().getUpperRightY();
                float factor = 2.83f;

                page.getStream();

                // add text
                contentStream.beginText();
                contentStream.setFont(font1, 10);
                contentStream.newLineAtOffset(factor * 60, startY - (factor * 53));
                contentStream.showText("test text" + i);
                contentStream.endText();

                contentStream.close();

                // import source page to output file->  Problem here ! new page contain old overlay text... 
                documentTarget.importPage(page);
            }
            documentTarget.save(fileTarget);
            documentTarget.close();
            documentSource.close();

        } catch (IOException e) {
            e.printStackTrace();
        }
        return fileTarget;
	}

Is there a way to have fresh page at every iteration ?
Thanks !

**Comment by TomRoush** [comment]
It looks like you're setting page to always be the first page.If you set ```PDPage page = documentSource.getDocumentCatalog().getPages().get(0);``` to be ```PDPage page = documentSource.getDocumentCatalog().getPages().get(i);``` does that fix your problem?
