### ISSUE TITLE
Ignore fonts

### ISSUE THREAD

**Issue by hot-cheese** [TomRoush/PdfBox-Android#69]
I managed to extract text from pdf file thanks to your awesome lib ;)
However what is need is just text and I don't care about its fonts. That's why I'd like to ignore loading or searching for fonts which (as I noticed) takes quite a lot of time. 
Is it somehow possible? For example by overriding FileSystemFontProvider?

**Comment by TomRoush** [comment]
Either FileSystemFontProvider or the ```org.apache.fontobx.util.autodetect``` package is where the fontloading code takes place. This may or may not be possible depending on what you do. You could also create a default font early in your application so that the fonts are all loaded before you try to do the text extraction.
