### ISSUE TITLE
implementation of PDFBox

### ISSUE THREAD

**Issue by hdrrocha** [TomRoush/PdfBox-Android#70]
hello, you have a simple example of how I could export an image to pdf using the lib PDFBox?

**Comment by TomRoush** [comment]
Sure. [This is the example code from Apache for inserting an image.](https://github.com/apache/pdfbox/blob/trunk/examples/src/main/java/org/apache/pdfbox/examples/pdmodel/AddImageToPDF.java) On Android, you would first load the image with `InputStream in = getAssets().open(imagePath);`. Then you create a PDImageXObject with either `PDImageXObject ximage = JPEGFactory.createFromStream(document, in);` or `ximage = LosslessFactory.createFromImage(document, BitmapFactory.decodeStream(alpha));` depending on what kind of image you are loading. Finally, you call `contentStream.drawImage(ximage, x, y);` to add to the PDF.

**Comment by hdrrocha** [comment]
hello, thank you for your answer haha I already managed to implement also
....
Now I have another problem, maybe you saba something that can help me ... I
need to make a picture with background virtue of calm to paste the PDF
file, you know something that I can use? I tried the "losslessfactory" but
without success yet.

2016-04-15 17:12 GMT-03:00 Tom Roush <notifications@github.com>:

**Comment by TomRoush** [comment]
What kind of image is it? If the image is JPEG you need to use JPEGFactory to create the XImage

**Comment by hdrrocha** [comment]
I can not let transparent background with JPEG Factory, the picture is
black, background need to stay virtue of calm to show what's behind the
image  =//
you have any examples of implementation of JPEGFactory? maybe I'm wrong
implementing the same

2016-04-15 17:30 GMT-03:00 Tom Roush <notifications@github.com>:

**Comment by TomRoush** [comment]
Are you compiling PDFBox from source or using the jCenter repository? LosslessFactory is only available if you build from source for now. Otherwise, can you show me the code that you're using?

**Comment by hdrrocha** [comment]
Trinket put my code in the following link:
https://github.com/hdrrocha/Images-with-transparent-background-Android-Java


2016-04-15 17:45 GMT-03:00 Tom Roush <notifications@github.com>:

**Comment by TomRoush** [comment]
Sorry for taking so long to respond. The code would look something like this: 
`
Bitmap vvvv = /* anything that gives you a Bitmap with transparency
PDImageXObject image = LosslessFactory.createFromImage(documentPdf, vvvv);
`
The rest of your code works just fine.
