### ISSUE TITLE
Extracting metadata from PDF

### ISSUE THREAD

**Issue by c4digit** [TomRoush/PdfBox-Android#71]
I’m not sure if I’ve come to the right spot for my question. Hopefully you can help me or direct me to someone who can help me
 
I’m currently using pdfbox-android with android studio
compile ‘org.apache: pdfbox-android:1.8.9.0’
 
My questions are
A) any metadata I try and get from a PDF is returning null ie getDocumentInformation.getTitle()
I know the document is being read as getNumberOfPages() returns the correct amount of pages.
Is this an known issue with V 1.8.9.0
I also know that the document has metadata as I can see it in the properties when I view it through adobe
 
B) is there a later android version I can reference? i.e compile ‘org.apache: pdfbox-android:1.8.11.0’
 
Thanks for your time

**Comment by TomRoush** [comment]
It seems to work properly for the PDFs I've tested it on. If you're still experiencing this issue, would it be possible to share a PDF that isn't working properly?
