### ISSUE TITLE
Invalid usage of group id org.apache

### ISSUE THREAD

**Issue by lehmi** [TomRoush/PdfBox-Android#72]
As I couldn't find any email address to contact the main contributor I've filed this issue.

I'm happy to see the effort to run Apache PDFBox on android and everything is fine w.r.t. to the license. 
But you must not use "org.apache" as groupid or as package prefix as this is limited to projects hosted at the apache software foundation only. Please change both. 

Thanks in advance

**Comment by TomRoush** [comment]
My apologies. I'll get this fixed as soon as possible.

**Comment by lehmi** [comment]
Any update on this issue? Do you need some help?

**Comment by TomRoush** [comment]
Thank you for your patience. All of the source files should have been updated with a new package. The current release version and all subsequent releases are being published under a new groupid.

**Comment by lehmi** [comment]
Thanks a lot, much appreciated!

Do mind if we recommend your port as one possible android port on our webpage?

**Comment by TomRoush** [comment]
No, I don't mind at all. I'm glad that you think it will be useful.
