### ISSUE TITLE
Creating transparent overlays doesn't seem possible

### ISSUE THREAD

**Issue by jverne** [TomRoush/PdfBox-Android#73]
With `PDPageContentStream#appendRawCommands()` deprecated and `PDResources#setGraphicsStates()` gone, I am completely at a loss as how to create a document with semi-transparent text on it. I eventually want to use this document as an overlay document.

I typically create a map with the extended graphics settings and then pass the raw command into the stream when creating the document as suggested here: https://issues.apache.org/jira/browse/PDFBOX-1176

Is there en equivalent for PDFBox-Android? I've tried various permutations of add() and put() on the page resources, but it looks like I need to get into the raw command stream somehow.

**Comment by TomRoush** [comment]
It should be possible to adapt that approach to work with the current code, but I'll have to look into it.

**Comment by TomRoush** [comment]
The setup code should look something like this:
```
PDExtendedGraphicsState extendedGraphicsState = new PDExtendedGraphicsState();
extendedGraphicsState.setNonStrokingAlphaConstant(0.5f);
PDResources resources = page.getResources();
COSName cosName = COSName.getPDFName("TransparentState");
resources.put(cosName, extendedGraphicsState);
```

You can then append to the command stream as needed.
