### ISSUE TITLE
Problem with adding a image with transparancy

### ISSUE THREAD

**Issue by MathiasKrill** [TomRoush/PdfBox-Android#74]
Hi, i try to add a image (handwriting sign) but all i tried did not lead to get it transparent. 

The following code does the job without transparancy: 

```

```
    public void addingImageToPDF(){

        File f = null;
        PDDocument pddDocument= null;
        PDFTextStripper textStripper = null;

        try {
            Log.i("pdfreading","enter  PDDocument.load(f);");

            Bitmap bitmap =  BitmapFactory.decodeFile(filedirectory + file_sub_path + "signImage.png");
            //Bitmap transBitmap = Bitmap.createBitmap(bitmap.getWidth(), bitmap.getHeight(), Bitmap.Config.ALPHA_8);

            f = new File(filedirectory , "/Android/data/demo/vertrag1.pdf");
            pddDocument = PDDocument.load(f);

            PDImageXObject pdImageXObject = null;
            pdImageXObject = JPEGFactory.createFromImage(pddDocument,bitmap);

            PDPage page =  pddDocument.getPage(0);
            PDPageContentStream pdfcontent = new PDPageContentStream(pddDocument, page,true,true);

            pdfcontent.drawImage(pdImageXObject,bitmap.getHeight(),bitmap.getWidth(),100.0f,100.0f);
            pdfcontent.close();

            String absolutepath = filedirectory + "/Android/data/demo/" +"vertrag1_result.pdf";

            pddDocument.save(absolutepath);

            // Most time this works - so you dont have to restart the device to see the created file in the Filesystem
            MediaScannerConnection.scanFile(this, new String[]{absolutepath},
                    null,
                    null);

        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }

```

if i try it with a transparent image (at least i hope it is transparent) i get the bad pdf "error_vertrag1" attached to this posting.

    public void addingImageToPDF(){

        File f = null;
        PDDocument pddDocument= null;

        try {
            Log.i("pdfreading","enter  PDDocument.load(f);");


            Bitmap bitmap =  BitmapFactory.decodeFile(filedirectory + file_sub_path + "signImage.png");

            Bitmap bitmaptransparent = createTransparentBitmapFromBitmap(bitmap, Color.WHITE);

            f = new File(filedirectory , "/Android/data/demo/vertrag1.pdf");
            pddDocument = PDDocument.load(f);

            PDImageXObject pdImageXObject = null;
            pdImageXObject = JPEGFactory.createFromImage(pddDocument,bitmaptransparent);

            PDPage page =  pddDocument.getPage(0);
            PDPageContentStream pdfcontent = new PDPageContentStream(pddDocument, page,true,true);

            pdfcontent.drawImage(pdImageXObject,bitmap.getHeight(),bitmap.getWidth(),100.0f,100.0f);
            pdfcontent.close();

            String absolutepath = filedirectory + "/Android/demo/demo/" +"vertrag1_result.pdf";

            pddDocument.save(absolutepath);

            // Most time this works - so you dont have to restart the device to see the created file in the Filesystem
            MediaScannerConnection.scanFile(this, new String[]{absolutepath},
                    null,
                    null);


        } catch (FileNotFoundException e) {
            e.printStackTrace();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }



    public static Bitmap createTransparentBitmapFromBitmap(Bitmap bitmap,
                                                           int replaceThisColor) {
        if (bitmap != null) {
            int picw = bitmap.getWidth();
            int pich = bitmap.getHeight();
            int[] pix = new int[picw * pich];
            bitmap.getPixels(pix, 0, picw, 0, 0, picw, pich);

            for (int y = 0; y < pich; y++) {
                // from left to right
                for (int x = 0; x < picw; x++) {
                    int index = y * picw + x;
                    int r = (pix[index] >> 16) & 0xff;
                    int g = (pix[index] >> 8) & 0xff;
                    int b = pix[index] & 0xff;

                    if (pix[index] == replaceThisColor) {
                        pix[index] = Color.TRANSPARENT;
                    } else {
                        break;
                    }
                }

                // from right to left
                for (int x = picw - 1; x >= 0; x--) {
                    int index = y * picw + x;
                    int r = (pix[index] >> 16) & 0xff;
                    int g = (pix[index] >> 8) & 0xff;
                    int b = pix[index] & 0xff;

                    if (pix[index] == replaceThisColor) {
                        pix[index] = Color.TRANSPARENT;
                    } else {
                        break;
                    }
                }
            }

            Bitmap bm = Bitmap.createBitmap(pix, picw, pich,
                    Bitmap.Config.ARGB_8888);

            return bm;
        }
        return null;
    }
```

What have i to do to get the sign image transparant ? (the white color, the black color should stay visible)  

- may you have some tipps for me - thank you in advanced.

[error_vertrag1.pdf](https://github.com/TomRoush/PdfBox-Android/files/297622/error_vertrag1.pdf)

![signimage](https://cloud.githubusercontent.com/assets/7436517/15779320/eecb5638-299b-11e6-9bcd-598d94b74191.png)
[vertrag1.pdf](https://github.com/TomRoush/PdfBox-Android/files/297607/vertrag1.pdf)
[vertrag1_result.pdf](https://github.com/TomRoush/PdfBox-Android/files/297608/vertrag1_result.pdf)

**Comment by TomRoush** [comment]
You'll need to use LosslessFactory instead of JPEGFactory to have transparency. LosslessFactory isn't in the currently released build, so you'll need to build the library from source or copy that one file into your project in order to get it to work.

**Comment by MathiasKrill** [comment]
Thank you Mr tom Roush - it worked with LosslessFactory :)
