### ISSUE TITLE
Draw a image on coordinates based on PDPage.getBBox().getWidth() & .getHeight()

### ISSUE THREAD

**Issue by MathiasKrill** [TomRoush/PdfBox-Android#75]
Hi, i try to print a image on a the coordinates based on the PDPage

 Log.i("pageinformation","pageinformation pdfbox: "+page.getBBox().getWidth() + " height: "+page.getBBox().getHeight());
// pageinformation pdfbox: 595.32 height: 841.92  

if i try to print the image on that place:

pdfcontent.drawImage (pdImageXObject,93.20f,615.0f,100f,100f);
pdfcontent.close();

it will appear on the wrong place: (i suppose)

![missmatch](https://cloud.githubusercontent.com/assets/7436517/15852844/f4075278-2ca2-11e6-8c3d-fb24578d2e36.png)

May you know what iam doing wrong ? - Thank you in advanced - best wishes Mathias

**Comment by MathiasKrill** [comment]
Update, it seems the y-value is inverted

**Comment by TomRoush** [comment]
In PDF coordinates, (0, 0) is the bottom left corner with positive y values going up.
