### ISSUE TITLE
Problems with PDFBoxResourceLoader

### ISSUE THREAD

**Issue by TomasKenny** [TomRoush/PdfBox-Android#76]
I am trying to deploy PdfBox in my project, however I have been unable to get it working properly so far. The first thing I did was adding pdfbox in Android Studio via File -> New -> New module -> import .aar package and I also added dependency on this project. Afterwards, apk was compiled fine and the text extraction from pdf which I am interested in was also working well. However the performance was poor (~30s), so before the extraction I added a call `PDFBoxResourceLoader.init(getApplicationContext());`
as was suggested in a different thread. The problem is that when I add this call, an exception is thrown:

`06-20 21:42:19.594 14036-14036/com.jedlik W/System.err: java.io.FileNotFoundException: /org/apache/fontbox/resources/cmap/Identity-H
06-20 21:42:19.596 14036-14036/com.jedlik W/System.err:     at android.content.res.AssetManager.openAsset(Native Method)
06-20 21:42:19.596 14036-14036/com.jedlik W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:339)
06-20 21:42:19.597 14036-14036/com.jedlik W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:313)
06-20 21:42:19.597 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.util.PDFBoxResourceLoader.getStream(PDFBoxResourceLoader.java:59)
06-20 21:42:19.597 14036-14036/com.jedlik W/System.err:     at org.apache.fontbox.cmap.CMapParser.getExternalCMap(CMapParser.java:414)
06-20 21:42:19.598 14036-14036/com.jedlik W/System.err:     at org.apache.fontbox.cmap.CMapParser.parsePredefined(CMapParser.java:86)
06-20 21:42:19.598 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.pdmodel.font.CMapManager.getPredefinedCMap(CmapManager.java:38)
06-20 21:42:19.598 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.pdmodel.font.PDType0Font.readEncoding(PDType0Font.java:142)
06-20 21:42:19.598 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.pdmodel.font.PDType0Font.<init>(PDType0Font.java:89)
06-20 21:42:19.599 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.pdmodel.font.PDFontFactory.createFont(PDFontFactory.java:65)
06-20 21:42:19.599 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.pdmodel.PDResources.getFont(PDResources.java:76)
06-20 21:42:19.599 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.contentstream.operator.text.SetFontAndSize.process(SetFontAndSize.java:32)
06-20 21:42:19.599 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:802)
06-20 21:42:19.600 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:464)
06-20 21:42:19.603 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:438)
06-20 21:42:19.604 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:147)
06-20 21:42:19.604 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.text.PDFTextStreamEngine.processPage(PDFTextStreamEngine.java:107)
06-20 21:42:19.604 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.text.PDFTextStripper.processPage(PDFTextStripper.java:334)
06-20 21:42:19.604 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.text.PDFTextStripper.processPages(PDFTextStripper.java:270)
06-20 21:42:19.605 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.text.PDFTextStripper.writeText(PDFTextStripper.java:235)
06-20 21:42:19.605 14036-14036/com.jedlik W/System.err:     at org.apache.pdfbox.text.PDFTextStripper.getText(PDFTextStripper.java:194)
06-20 21:42:19.605 14036-14036/com.jedlik W/System.err:     at com.jedlik.MainActivity.readFile(MainActivity.java:36)
06-20 21:42:19.605 14036-14036/com.jedlik W/System.err:     at com.jedlik.MainActivity$DownloadMenuPdfAsyncTask.onPostExecute(MainActivity.java:139)
06-20 21:42:19.605 14036-14036/com.jedlik W/System.err:     at com.jedlik.MainActivity$DownloadMenuPdfAsyncTask.onPostExecute(MainActivity.java:95)
06-20 21:42:19.605 14036-14036/com.jedlik W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:651)
06-20 21:42:19.606 14036-14036/com.jedlik W/System.err:     at android.os.AsyncTask.access$500(AsyncTask.java:180)
06-20 21:42:19.606 14036-14036/com.jedlik W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
06-20 21:42:19.606 14036-14036/com.jedlik W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
06-20 21:42:19.606 14036-14036/com.jedlik W/System.err:     at android.os.Looper.loop(Looper.java:224)
06-20 21:42:19.608 14036-14036/com.jedlik W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5526)
06-20 21:42:19.608 14036-14036/com.jedlik W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
06-20 21:42:19.608 14036-14036/com.jedlik W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-20 21:42:19.608 14036-14036/com.jedlik W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

Does anybody know how to fix it??

Interesting foundings:

- unpacked apk contains assets folder with the file assets\org\apache\fontbox\resources\cmap\Identity-H as one would expect (checked in total commander)
- when I added a breakpoint inside method AssetManager::open(String fileName, int accessMode), various other assets from path assets\org\apache\pdfbox (not fontbox) are read without any errors

Configuration:
Android studio 1.4
compileSdkVersion and targetSdkVersion 23
tested on hw Sony Xperia Z3 compact (Marshmallow)

**Comment by TomasKenny** [comment]
Not sure what the actual problem was but I solved it by compiling PdfBox-Android sources in my project and not using the .aar package.

**Comment by TomRoush** [comment]
It looks like this is a bug in the current release. A new release should be coming out soon.
