### ISSUE TITLE
Using PDFBox 2

### ISSUE THREAD

**Issue by markmelling** [TomRoush/PdfBox-Android#77]
How straight-forward is the process of moving PdfBox-Android  so that it is based on a PDFBox 2 release?

Is there something more that just coping the latest PDFBox 2 source files over? If not can you outline the steps involved.

Thanks

**Comment by TomRoush** [comment]
Unfortunately it's not quite that simple. While the majority of Java is directly compatible with Android, some parts, especially any code that relates to graphics, will need to be rewritten with the correct Android method calls. If you try to copy the Java code into an Android project, you'll get lots of errors when you try to compile. You need to go through and fix the errors by determining how to accomplish the same thing using the Android classes.

**Comment by ashughes** [comment]
I just added the latest official build on Android and it appears to work (it compiled):

    compile 'org.apache.pdfbox:pdfbox:2.0.5'

Haven't done any implementation yet, however.

**Comment by ashughes** [comment]
Okay, so after actually implementing a few things, everything compiles, but then I receive runtime errors. For example:

    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/color/ColorSpace;

I'm not actually trying to use any Java AWT classes, however, it must just be because classes I am using are attempting to load these classes. :-/
