### ISSUE TITLE
How to write bullet points?

### ISSUE THREAD

**Issue by gjnidea** [TomRoush/PdfBox-Android#82]
Hi, first of all I want to thank you for your efforts on this one. It really helped a lot of people.

As for my question, I think this is related to [this issue](https://github.com/TomRoush/PdfBox-Android/issues/40) which was submitted a year ago. Seeing as bullet is a special character, I want to know if this is possible now. I saw from this [thread](http://stackoverflow.com/questions/32179700/create-a-bullet-list-item-using-pdfbox) that it is possible with pdfbox 2.0 but I think this library isn't updated yet to that version.

Thanks again for this port!

**Comment by TomRoush** [comment]
It is possible if you use the LiberationSans font for example. You may still have trouble using other unicode characters, but I was able to get the bullet point to write to a PDF.
