### ISSUE TITLE
Form Field creation

### ISSUE THREAD

**Issue by glelan** [TomRoush/PdfBox-Android#85]
Hello more question that issue : is it possible to create Form Filed (textbox, checkbox, combobox and signature) using this library ? I would like to scan an existing pdf to find "keyword" and for each keyword create a checkbox or textbox on it.
Thanks

**Comment by TomRoush** [comment]
[See here for an example. ](https://github.com/apache/pdfbox/blob/1bf5fb7b4c16ba7bf55f178182ef9decb136a58b/examples/src/main/java/org/apache/pdfbox/examples/acroforms/CreateFormField.java) Lines 44 and 45 are different on Android, take a look at the sample app [here](https://github.com/TomRoush/PdfBox-Android/blob/master/sample/src/main/java/org/apache/pdfboxandroid/sample/MainActivity.java) for an example of setting up fonts.
