### ISSUE TITLE
Extract images from PDF file

### ISSUE THREAD

**Issue by rafaelpivetta** [TomRoush/PdfBox-Android#86]
How can this library be used to extract all images from PDF file?

**Comment by TomRoush** [comment]
[Take a long at this example.](https://github.com/apache/pdfbox/blob/04292e421e9531616aa2856b908fbdb05b381af7/tools/src/main/java/org/apache/pdfbox/tools/ExtractImages.java) Most of the write2file method can be replaced by something like this:
```
File file = new File(android.os.Environment.getExternalStorageDirectory().getAbsolutePath() + "/Download/" + name +".jpg");
FileOutputStream fOut = new FileOutputStream(file);
pdImage.getImage().compress(Bitmap.CompressFormat.JPEG, 100, fOut);
```
