### ISSUE TITLE
Cannot find LosslessFactory

### ISSUE THREAD

**Issue by DariusL** [TomRoush/PdfBox-Android#87]
Just added a dependency on 1.8.9.0 instead of the source directly and I can't find `LosslessFactory` tried invalidating caches, cleaning.

**Comment by TomRoush** [comment]
The 1.8.9.0 release doesn't have the LosslessFactory class. You can either compile from source or use `com.tom_roush:pdfbox-android:1.8.9.1` in your dependencies instead.

**Comment by DariusL** [comment]
At the time there was no 1.8.9.1 build, so I compiled it myself. Forgot to close this.
