### ISSUE TITLE
Render Image Error

### ISSUE THREAD

**Issue by khaledsamer** [TomRoush/PdfBox-Android#88]
when i try to render the image inside the file it gives me this error :: 

10-26 09:22:57.816 474-474/com.example.khaledsamer.myapplication W/System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.graphics.Bitmap.getWidth()' on a null object reference
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.rendering.PageDrawer.drawBufferedImage(PageDrawer.java:744)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.rendering.PageDrawer.drawImage(PageDrawer.java:713)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.contentstream.operator.graphics.DrawObject.process(DrawObject.java:35)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processOperator(PDFStreamEngine.java:802)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processStreamOperators(PDFStreamEngine.java:464)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processStream(PDFStreamEngine.java:438)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.contentstream.PDFStreamEngine.processPage(PDFStreamEngine.java:147)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.rendering.PageDrawer.drawPage(PageDrawer.java:118)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.rendering.PDFRenderer.renderPage(PDFRenderer.java:124)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at org.apache.pdfbox.rendering.PDFRenderer.renderImage(PDFRenderer.java:87)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at com.example.khaledsamer.myapplication.PDFTest.renderFile(PDFTest.java:137)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.view.View.performClick(View.java:4756)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.view.View$PerformClick.run(View.java:19749)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5221)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
10-26 09:22:57.817 474-474/com.example.khaledsamer.myapplication W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
10-26 09:22:57.818 474-474/com.example.khaledsamer.myapplication I/Choreographer: Skipped 118 frames!  The application may be doing too much work on its main thread.

**Comment by TomRoush** [comment]
What does the code that generates this error look like?

**Comment by khaledsamer** [comment]
your sample code 
but i found the problem . the problem was in the pdf file idk why he can't getWidth();  when i changed the file it works but it gives me white blank paper . why ?

**Comment by TomRoush** [comment]
It's possible that the files you have are using a type of image that isn't yet supported. Would you be able to share the files?
