### ISSUE TITLE
Failed to resolve: com.tom_roush.pdfbox-android:1.8.9.1

### ISSUE THREAD

**Issue by kal27** [TomRoush/PdfBox-Android#89]
I'm trying to add the library to my gradle build and this is what i get 

`Error:Failed to resolve: com.tom_roush.pdfbox-android:1.8.9.1:`

I'm also having trouble finding the project in the maven repository

**Comment by lhoracek** [comment]
There is no file in the bintray repositories

**Comment by TomRoush** [comment]
Typo in the readme. It should be ` compile 'com.tom_roush:pdfbox-android:1.8.9.1' ` What seems to be wrong with the metadata files?

**Comment by lhoracek** [comment]
Nothing, my bad :-)
