### ISSUE TITLE
Highlight text

### ISSUE THREAD

**Issue by bennytalent** [TomRoush/PdfBox-Android#90]
Is it somehow possible to search and highlight text in a pdf with this library? I found the class PDFHighlighter but I don't know how to use it. Could someone maybe give me an example code snippet?
Thank you very much in advance!

EDIT:

        try {
            PDDocument doc = new PDDocument();
            Writer writer;
            AssetManager assetManager = getActivity().getAssets();
            doc = PDDocument.load(assetManager.open("sample.pdf"));
           
            writer = new FileWriter(getActivity().getFilesDir() + "test.xml");
            PDFHighlighter pdfHighlighter = new PDFHighlighter();
            pdfHighlighter.generateXMLHighlight(doc, "<searched text>", writer);
           
        } catch (IOException e) {
            e.printStackTrace();
        }
        finally {
            try {
                doc.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

These lines of code create a xml-file with the position of the searched text but only for the first page of the pdf.

My questions:
How can I do this for the whole pdf and how do I use the xml-file to highlight the text?

**Comment by bennytalent** [comment]
I found a different solution and closed the issue.

**Comment by Abdul-Aziz-Niazi** [comment]
Please share the solution you've found

**Comment by bennytalent** [comment]
I used the library "mupdf".
