### ISSUE TITLE
Getting NoClassDefFoundError in the newer version of the library.

### ISSUE THREAD

**Issue by YugankaS** [TomRoush/PdfBox-Android#93]
A few months ago, I was using "compile 'org.apache:pdfbox-android:1.8.9.0'" in gradle and PdfBox was working properly. I got involved in other modules of the app I am working on, and didn't use this part of the app.

Now when I am trying to use it, it is giving a NoClassDefFoundError. A little searching around and I realised I had to change the gradle to "compile 'com.tom_roush:pdfbox-android:1.8.9.1'", which I did.

But it is still not working -  
1. I am still getting NoClassDefFoundError.
2. PdfBox-Android is based on PdfBox v1.8.9, whereas the latest version of PdfBox is 1.8.13. Could this be a reason?
3. On the main page, it is mentioned that PdfBox-Android "depends on the following libraries: SpongyCastle core, prov, and pkiv: ". However, when I visit the SpongyCastle page on github, I cant find any pkiv library, only pkix library.

Any help will be appreciated.

**Comment by jverne** [comment]
Yes, the package name changed because org.apache is not allowed by others. As a far as I know, nothing has changed with respect to required libs. If you bring in only pdf box android, gradle will find the rest for you.

**Comment by TomRoush** [comment]
1. What specific error are you getting? Does it say that a specific class is missing?
2. The code in this library is based on the code from the desktop version at 1.8.9. That means that if any changes / features added in 1.8.10 - 1.8.13 won't be present in the library.
3. That was a typo in the README that has been corrected. jverne is right, if you are using gradle to build, the dependencies are already taken care of.

If for some reason 1.8.9.1 isn't working for you, you can try 1.8.9.0. Gradle should still be able to find the old version, but you will be missing some features and bug fixes.

**Comment by YugankaS** [comment]
Hello jverne and Tom, thank you both for your reply.

Tom, there is some inconsistency in the functioning of the library - it doesn't function all the times I use it, even though I haven't changed my code.

**1**. It gives a NoClassDefFoundError on the first line where any class of PdfBox-Android is used. For example, you have recommended that we should call 

PDFBoxResourceLoader.init(getApplicationContext()); 

before using the library, so it gave the error there. Then, just to see if the problem was restricted to this class, I removed this line, but then it started giving the error on com.tom_roush.pdfbox.pdmodel.PDDocument, my next usage of a class of the library.

**2**. Sometimes, it runs on wifi but not on mobile data. And then, the very next time I try to use the library, it gives a NoClassDefFoundError, even though I haven't changed a single letter in the code. This is strange.

If this was somehow caused by restrictions put on the wifi network I am using at office, the library shouldn't have worked on wifi, but surely should have worked on mobile data where I have put no restrictions. The fact that precisely the reverse is happening confounds me.

Also, network issues wouldn't have given a NoClassDefFoundError anyway.

**Comment by jverne** [comment]
My app does the same thing, and with 1.8.9.1 all I had to do is update the package names in the import statements in a few classes. Maybe post a stacktrace?

It occurs to me that Android Studio/Gradle can get a little stupid sometimes when dependencies change, and it may be caching the old package names. Maybe try the "reset caches and restart" option in Android Studio? It is a bit like the nuclear option, but it sometimes solves weird problems.

**Comment by TomRoush** [comment]
Now that I think about it, I think I've had this happen before. I think I tried a gradle clean and that didn't fix the issue, but I believe deleting the build folders and rebuilding fixed the issue. Resetting the cache might do the same thing, it certainly can't hurt to try it.

-----Original Message-----

**Comment by YugankaS** [comment]
Alright, let me try this out. :-)

**Comment by YugankaS** [comment]
Okay, it is working now. Thank you jverne and Tom. :-) 

I'd be really grateful if you could solve one other problem I am facing - some of the pdfs formed are corrupted - 

E/PdfBoxAndroid: Can't find the object axref table/stream at offset 219111
E/PdfBoxAndroid: Skipped XRef stream due to a corrupt offset:0

What I am trying to do - reading an amazon s3 object using an InputStream and then writing it using an outputstream into a local file, while applying watermarking on it.

Thank you!
