### ISSUE TITLE
unable use saveIncremental with inputstream

### ISSUE THREAD

**Issue by lkarthik76** [TomRoush/PdfBox-Android#95]
in pdfbox.1.8. have api to call saveIncremental with inputstream. is there same function ?

**Comment by TomRoush** [comment]
Is `void saveIncremental(OutputStream output)` in PDDocument the method you're looking for? There is no saveIncremental method that takes in an InputStream.

**Comment by lkarthik76** [comment]
i am looking same as PDFbox1.8 in PDDocumnet has public void saveIncremental(InputStream input, OutputStream output) throws IOException, COSVisitorException. is there same api ? or is that possible have the same ?

**Comment by TomRoush** [comment]
I haven't have a chance to verify yet, but if you copy the saveIncremental method [from here](https://github.com/apache/pdfbox/blob/1.8/pdfbox/src/main/java/org/apache/pdfbox/pdmodel/PDDocument.java#L1399) into pdmodel/PDDocument.java and build the library, the method should work.
