### ISSUE TITLE
PdfRenderer issues with scale

### ISSUE THREAD

**Issue by talosdev** [TomRoush/PdfBox-Android#97]
I don't know how this relates to #64.

I am trying to render a PDF file with a scaling factor of > 1. And the code is not working as 

``` 
PDFRenderer renderer = new PDFRenderer(document);
Bitmap bitmap = renderer.renderImage(0, 2, Bitmap.Config.ARGB_8888);
ximage = JPEGFactory.createFromImage(doc, bitmap);
```

```Renderer.renderImage``` correctly creates a bitmap twice as big as the page's cropbox, but then although the new ```width```, ```height``` and the ```scale``` factor are passed over to the ```renderImage``` method, they are not user at all.
So the bitmap has double dimensions, but the page is printed using the original size, so we get everything printed out in the upper left quarter of the bitmap, and the rest of the bitmap is blank.

The expected behaviour is the one we get with the native PdfRenderer and the following code:
```
PdfRenderer.Page page = renderer.openPage(0);
int h = 2 * page.getHeight();
int w = 2 * page.getWidth();
Bitmap bitmap = Bitmap.createBitmap(w, h, Bitmap.Config.ARGB_8888);
Rect rect = new Rect(0, 0, w, h);
page.render(bitmap, rect, null, PdfRenderer.Page.RENDER_MODE_FOR_DISPLAY);
page.close();
ximage = JPEGFactory.createFromImage(doc, bitmap);                   
```

 Using version 1.8.9.1

**Comment by TomRoush** [comment]
Similar issue I think. I suspect that the previous fix is now causing problems for some reason.

**Comment by hjgode** [comment]
In PDFRendere.java in public void renderPage(PDPage page, Paint paint, Canvas canvas, int width, int height, float scaleX, float scaleY) throws IOException add following after the if (rotation...) block:

    canvas.scale(scaleX,scaleY);

**Comment by leosimas** [comment]
Hi, @TomRoush.
When this fix will be available in a release version?

**Comment by TomRoush** [comment]
New version with this fix has been released
