### ISSUE TITLE
Replace Existing Image in PDF with new Image from Asset Folder

### ISSUE THREAD

**Issue by Sharathmk99** [TomRoush/PdfBox-Android#99]
Hi,

I want to replace existing Image in PDF with another Image, but no luck. 
Please see below code i tried,

PDDocument document = PDDocument.load(assetManager.open("sample.pdf"));
OutputStream os = null;
InputStream is = null;
PDImageXObject img1 = null;
PDResources resources = document.getPage(0).getResources();
Iterable<COSName> xObjectNames = resources.getXObjectNames();
if (null != xObjectNames) {
	for(COSName xObjectName : xObjectNames){
		PDXObject object = resources.getXObject(xObjectName);
		Log.v("Message", xObjectName.getName());
		if (object instanceof PDImageXObject) {
			if(xObjectName.getName().equalsIgnoreCase("IMwJWtoXMb")){
				img1 = (PDImageXObject) object;
				//img1.getCOSStream().clear();
				os = img1.getCOSStream().createFilteredStream();
				//img1.getCOSStream().clear();
			}else if(xObjectName.getName().equalsIgnoreCase("IMKtZnAsTG")){
				img1 = (PDImageXObject) object;

				is = img1.getCOSStream().getUnfilteredStream();
			}

		}
	}
	IOUtils.copy(getAssets().open("profile.png"), os);
	is.close();
	os.close();

}
document.save(path);
document.close();

Please help

**Comment by Sharathmk99** [comment]
@TomRoush Please help

**Comment by TomRoush** [comment]
```
// setup document and resources
String tagOfImageToReplace = // either IMwJWtoXMb or IMKtZnAsTG in your case
PDImageXObject newImage = // create a PDImageXObject for the replacement image
resources.put(COSName.getPDFName("tagOfImageToReplace"), newImage);
// save and close
```
should do it. This works if the old and new images are the same size, but if they're different it probably won't.
